### ISSUE TITLE
GH action to open PRs in client repos when nexus.json spec changes

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/omicron#1140]
## Background
Currently the generated clients and docs repo are updated when a human finds out that there have been changes in the `nexus.json` OpenAPI spec.

This means that at times we might not realise there have been changes, and can take a bit longer to update the clients. Additionaly, if no one notices we get to a point where too many changes have been made. Updating the clients can become cumbersome.

## Expected outcome
We should have a mechanism that alerts us when a change has been made to the external OpenAPI spec.

## Plan of attack
A good way forward is to have a GH action that opens up PRs in all clients and docs repo whenever a change has been made to the `nexus.json` file.

To keep it simple, for now this GH action will only open a PR that changes the omicron commit hash in each [`VERSION_OMICRON`](https://github.com/oxidecomputer/oxide.rs/blob/main/VERSION_OMICRON.txt) file. From there, a human will still be in charge of generating the clients and making sure nothing has been broken.

Once we are confident in the client/docs generation we can automate more steps.

**Comment by smklein** [comment]
This is a good idea - @zephraph discussed this as a pain-point while spinning up Omicron + the console for last week's dry-run. I believe the TL;DR of dependencies is that:

- Omicron hosts the API, via that `nexus.json` file
- Console depends on the [Omicron version](https://github.com/oxidecomputer/console/blob/main/OMICRON_VERSION), since it relies on the Omicron API...
- ... but Omicron also depends on the [console bundle](https://github.com/oxidecomputer/omicron/blob/main/tools/console_version), since it bundles it into the Nexus zone package.

(the dependency chain through `oxide.rs` + the CLI is similar - although Omicron doesn't explicitly depend on the CLI)

Though an automated pipeline to keep everything up-to-date definitely works, in the case of the console, this is fundamentally a circular dependency - we could also be open to other solutions that re-arrange dependencies to make the chain non-circular.

@zephraph / @david-crespo , do you have strong opinions?

**Comment by david-crespo** [comment]
We could just leave console out of it. I have a feeling Karen was talking about the language clients and not Console itself.

**Comment by zephraph** [comment]
Alternatively we could only focus on the story for opening a PR for console and not vice versa. It's something I've already wanted to automate anyway (and it's been made much easier by reducing the moving parts in console).

The circular dependency doesn't really need to be a circular dependency. If we're wanting to spin up nexus with console we essentially need a utility that can say "what's the latest version of Nexus that the console actually supports?" That's what we're doing with the reverse pin, it's just more manual. This is orthogonal to the original question though. I think keeping console up-to-date with nexus changes is definitely something that we should do though.

**Comment by karencfv** [comment]
No longer necessary since we have https://github.com/oxidecomputer/reflector now
