### ISSUE TITLE
Return a flag in disk GET to denote if deletion is allow

### ISSUE THREAD

**Issue by zephraph** [oxidecomputer/omicron#1323]
Currently clients have to replicate [this logic](https://github.com/oxidecomputer/omicron/blob/e5704d7f343fa0633751527dedf276409647ad4e/nexus/src/db/datastore.rs#L2103) to deduce whether a disk can be deleted. It'd easy downstream implementation if we just encoded this into the disk response.

**Comment by david-crespo** [comment]
I'm ambivalent. Even if you get this on a response, it's only true at the time of the request. If you're using it to determine what the UI should look like, you are still immediately at risk of it becoming wrong. Of course, that is equally true of what we're currently doing — looking at the disk state and applying our own (potentially wrong) copy of the API logic to determine whether it's deletable. So I can see the value here being that we at least eliminate one potential source of error.

Even so, this feels wrong to me, like it's encoding too much frontend logic into the API. The obvious counterpoint: deletability is clearly API logic, it just happens to be highly relevant to the frontend. Surely that relevance is an argument _in favor_ of including it, not against it.

Maybe my bad feeling is more about what happens when you take this reasoning to its logical conclusion: we would end up filling the whole API up with a lot of noise. For disks, we don't just need `deleteable`, we need `attachable` and `detachable`. And on instances we'd need the whole state machine for when stop, start, and delete are allowed (see [console logic for this](https://github.com/oxidecomputer/console/blob/480ddc2c3709530daf974d4a0a2f6b40f0205b77/app/pages/project/instances/actions.tsx#L11-L16)). That seems like too much.

**Comment by zephraph** [comment]
Fair point.
