### ISSUE TITLE
RSS -> Nexus handoff plumbing

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#1528]
RSS must provide operators a way to "add sufficient networking configuration to be able to launch Nexus, and continue setup through the web console".

The current implementation is somewhat limited in this regard - although `config-rss.toml` - representing user input - can contain an external address for Nexus, there are shortcomings:
- It's limited to a single address
- There is no mechanism to supply server certificates to encrypt traffic

**Comment by smklein** [comment]
See: `sled-agent/src/rack_setup/config.rs`

**Comment by smklein** [comment]
https://github.com/oxidecomputer/omicron/issues/1959 provides more detail about the x509 transfer

**Comment by davepacheco** [comment]
I'm putting this on the MVP board because I think it covers work that we plan to do for then.  I think all that's missing here is to plumb the certificate list from RSS's API to Nexus's.  That is, it's already in Nexus's API.  What's left is accepting this in RSS's API, which means figuring out what should go into the config files we use in dev/test.

**Comment by smklein** [comment]
RSS is already passing TLS certs to Nexus, through the internal API: https://github.com/oxidecomputer/omicron/blob/9070c6bc822e22efdc6d9b0f7b1c364f8b1c23f9/nexus/types/src/internal_api/params.rs#L242-L243

**Comment by smklein** [comment]
Ah, luqman corrected me, there is still this TODO: https://github.com/oxidecomputer/omicron/blob/9070c6bc822e22efdc6d9b0f7b1c364f8b1c23f9/sled-agent/src/rack_setup/service.rs#L745-L759

So this part is still to-do -- it's the handoff of the TLS certs from wicket/wicketd (via the bootstrap network) to RSS itself
