### ISSUE TITLE
Partial Failure in RSS setup can cause hang due to sled agent setup

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#1879]
- Suppose RSS gets partway through setup, and fails, for whatever reason. Suppose that all sleds have bootstrap agents which know how to start sled agents. This information is recorded durably, so sled agents can reboot autonomously from that point onwards. This is important - remember, the sled agents will be booting on their own from this point.
- On reboot, RSS should attempt to re-inject the requests, using the same `rss-plan.toml` file.
- If it does this, RSS will be stuck here:

https://github.com/oxidecomputer/omicron/blob/b4366f1561f710653e4759685632ead91311a8e7/sled-agent/src/rack_setup/service.rs#L560-L576

- This call to `initialize_sleds` ends up blocked on a request to bootstrap agents, for them to initialize their sled agents: 

https://github.com/oxidecomputer/omicron/blob/f8f076ad10092ea10a44646e46270c69aa6dff84/sled-agent/src/bootstrap/rss_handle.rs#L92-L105

- I can see in the logs, this returns the following error from the bootstrap agent itself:

https://github.com/oxidecomputer/omicron/blob/b4366f1561f710653e4759685632ead91311a8e7/sled-agent/src/bootstrap/server.rs#L362-L368

**I believe this is a bug - instead of returning `Ok(())`, RSS will be stuck behind a sled agent that booted by itself**.

@jgallagher , WDYT - would it be okay to just idempotently return `Ok` if the sled agent already exists?

**Comment by jgallagher** [comment]
This is exactly what @Nieuwejaar ran into yesterday; thanks for writing this up. I don't think we can return `Ok(_)` here; we would need to check that `request` and `trust_quorum_share` match the values that our sled agent used when it started, and the `trust_quorum_share` is guaranteed NOT to match unless it's disabled entirely:

* RSS [generates a new rack secret](https://github.com/oxidecomputer/omicron/blob/b4366f1561f710653e4759685632ead91311a8e7/sled-agent/src/rack_setup/service.rs#L535-L540) on startup, which is intentionally not persisted
* If RSS got partway through initialization and distributed secret shares to some sleds which recorded them, but is now rerunning with a new rack secret, we'll end up with some sleds using old shares and some sleds using new shares

This problem of partial initialization is a big part of the (or maybe the primary?) motivation for the `bootstore` work @andrewjstone started but has paused to do MUP/wicket things. I'm not entirely sure what to suggest we do in the meantime - we could put in checks on `request` and `trust_quorum_share` and return `Ok(_)` if they match, knowing that in practice that will only work for single-sled systems? I believe `request_agent()` already has a check like this, so maybe we could change this to something like

```rust
        Request::SledAgentRequest(request, trust_quorum_share) => {
            let trust_quorum_share =
                trust_quorum_share.map(ShareDistribution::from);

            match bootstrap_agent
                .request_agent(&request, &trust_quorum_share)
                .await
            {
                Ok(response) => {
                    Ok(Response::SledAgentResponse(response))
                }
                Err(err) => {
                    warn!(log, "Sled agent request failed"; "err" => %err);
                    Err(format!("Sled agent request failed: {err}"))
                }
            }
        }
}
```

which is similar to the handler in `serve_request_before_quorum_initialization()` above. This will still fail if multiple sleds are involved, but (a) it's better than today, particularly for single-sled dev work and (b) the error message should be [more obvious](https://github.com/oxidecomputer/omicron/blob/b4366f1561f710653e4759685632ead91311a8e7/sled-agent/src/bootstrap/agent.rs#L250-L262).

**Comment by andrewjstone** [comment]
I think putting in the checks for the `trust_quorum_share` matching is probably the right short term solution here. Although, as @jgallagher mentions if we have a real rack secret the shares will *never* match because RSS will always generate a new random shared secret. However a real rack secret will only be needed on a multi-node system which we aren't currently testing. The multi-node partial initialization will eventually be fixed by the bootstore work, and I don't think we should put any effort into trying to solve it with the code as it is currently structured. What this all means then, is that we can probably just check if the `trust_quorum_share ==None`, and if so just ignore the re-initialization and return `Ok(())` as @smklein suggests.

**Comment by davepacheco** [comment]
See #1880 for context.  The sled-agent log is also there for more details about how this manifested.  (It sounds like y'all already understand the behavior well enough but I figured I'd drop this here for the record.)

In that case, we ran into a problem setting up the CockroachDB zone and sled-agent was explicitly restarted before that finished.  We were surprised to find that RSS was apparently not trying to finish setup.  It was, actually, but it was stuck in this phase of initializing sled agents because of the "already initialized" error.
