### ISSUE TITLE
thread 'integration_tests::instances::test_instance_metrics' panicked at 'attempt to subtract with overflow'

### ISSUE THREAD

**Issue by iliana** [oxidecomputer/omicron#2186]
https://github.com/oxidecomputer/omicron/runs/10768352787 / https://buildomat.eng.oxide.computer/wg/0/details/01GQ6DS2KJ0QDM6YWDNRZDTCHZ/B44Zl5JIuOAhkn5GInFdH46LbPhq8Dq00FztPZBK0cQJCm5s/01GQ6DSB1H70J2FKRWK36STEQ6#S11679:

```
---- integration_tests::instances::test_instance_metrics stdout ----
--
log file: /var/tmp/omicron_tmp/test_all-df03734e17da7df2-test_instance_metrics.51359.58.log
note: configured to log to "/var/tmp/omicron_tmp/test_all-df03734e17da7df2-test_instance_metrics.51359.58.log"
thread 'integration_tests::instances::test_instance_metrics' panicked at 'attempt to subtract with overflow', nexus/tests/integration_tests/metrics.rs:33:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
WARN: dropped CockroachInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
WARN: temporary directory leaked: /var/tmp/omicron_tmp/.tmpm1YIU2
WARN: dropped ClickHouseInstance without cleaning it up first (there may still be a child process running and a temporary directory leaked)
```

https://github.com/oxidecomputer/omicron/blob/d6dc72f6a5339296193f1a47310ced437aa39aa1/nexus/tests/integration_tests/metrics.rs#L26-L39

This panics if `measurements.items.len() == 0`.

**Comment by smklein** [comment]
Almost definitely a result of https://github.com/oxidecomputer/omicron/pull/1782 ; I can look

**Comment by smklein** [comment]
Here's what that test is *supposed* to be doing...

We're supposed to be querying the "project" and "org" we created to see how much space they report to be using.

We first do that by querying the DB for those values, which indicates they've been inserted: https://github.com/oxidecomputer/omicron/blob/d6dc72f6a5339296193f1a47310ced437aa39aa1/nexus/tests/integration_tests/instances.rs#L545-L553

We also want to query the Nexus API, to test that the metrics are being offloaded to Clickhouse and Oximeter properly.

So we check the utilization URL: https://github.com/oxidecomputer/omicron/blob/d6dc72f6a5339296193f1a47310ced437aa39aa1/nexus/tests/integration_tests/instances.rs#L555-L562

HOWEVER, these metrics might not live in Clickhouse after inserting these values into Nexus. This would mean a call to the utilization URL fails, since no data exists. Nexus collects metrics by storing them locally, then offloading them to Clickhouse through Oximeter. In Oximeter's language, Nexus is a "producer" of metrics, that is periodically polled.

... I tried to avoid this by calling https://github.com/oxidecomputer/omicron/blob/d6dc72f6a5339296193f1a47310ced437aa39aa1/nexus/tests/integration_tests/instances.rs#L563

Which *should* be forcing Oximeter to collect the metrics from Nexus and dump 'em to Clickhouse:
https://github.com/oxidecomputer/omicron/blob/e69a5a34e8f357e71044956172c6c06ef5d38161/oximeter/collector/src/lib.rs#L550-L556

I wasn't *totally* sure if there was some delay along the Oximeter --> Clickhouse pathway, but I can look at that now.

It seems `collection_task`, which operates on the `CollectionMessage::Collect` message, issues `perform_collection`, which writes the result to an `mpsc::Sender`. Looks like this "sender" is cloned from the `OximeterAgent::result_sender`, so it looks like the `OximeterAgent::result_receiver` (the receiving end of this channel) gets sent to a function called `results_sink`... which looks like it's added to a batch that only is emitted when it crosses certain size threshold or a timeout is crossed. Hrm. This might be causing a longer delay than expected.

I suppose it's possible that this delays the transfer of metrics from Nexus -> Oximeter -> Clickhouse, which would result in this error where "no metrics are visible in Clickhouse". I'll add a PR to fix that behavior.
