### ISSUE TITLE
Dropping VNICs: Make a futureunordered to eat the vnics

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#2656]
As seen during dogfood setup, the sled agent tried to make a zone (oxz_nexus).

For reasons that do not really matter, Nexus died. 

In the logs, we saw this:

```
Failed to delete Link: Failed to delete vnic oxControlService89: Command [/usr/sbin/dladm delete-vnic oxControlService89] executed and failed with status: exit status: 1  stdout:   stderr: dladm: vnic deletion failed: link busy
Failed to delete Link: Failed to delete vnic oxControlPublic39: Command [/usr/sbin/dladm delete-vnic oxControlPublic39] executed and failed with status: exit status: 1  stdout:   stderr: dladm: vnic deletion failed: link busy
```

TL;DR: When the zone is getting torn down, the VNICs are still in use *somewhere*.

Chatting with @bnaecker , here are our conclusions:
- We don't know what interface we could use to ask the OS "when is this vnic no longer in use" -- such an interface may not exist.
- We *do* still want the sled agent to delete this vnic.

To resolve:
- We should make the `drop` functionality for VNICs hand off to an out-of-band queue, where they can be deleted asynchronously w.r.t. the drop function. This should basically just be a task that is re-trying to delete the vnics whenever they can be deleted.

**Comment by jclulow** [comment]
FWIW, even if we had an interface that could tell you _some_ of the things that might be holding it open, I think that there are always going to be places where it's just a reference count and all we know is it hasn't gone to 0 yet.  As with all reference county things, it might be stuck above zero because of a bug where we forgot to drop the reference count, as well.

I think that means we'll want to consider:

- this might be a condition that _never_ terminates for a particular VNIC; we should keep retrying forever, but not let one stuck VNIC at the head of the queue block the destroy queue for other VNICs that are probably not stuck
- if a VNIC remains invulnerable for some length of time, that's a fact we want to hear about as some kind of reported soft failure that is likely the result of a software defect

This is also a property of other system resources we will be trying to tear down in future, like zones or file systems or even in some cases processes that we'd like to kill but seemingly cannot.

**Comment by luqmana** [comment]
So there's also https://github.com/illumos/ipd/blob/master/ipd/0003/README.adoc which @citrus-it recently updated and has a [CR](https://code.illumos.org/c/illumos-gate/+/2662) out for. The relevant bit specifically is:

>Upstream the core transient link feature from SmartOS. That is, add a transient flag for links that causes them to be automatically removed when a zone halts;

**Comment by rmustacc** [comment]
@luqmana That's already in stlouis so it could be used today if desired.

**Comment by luqmana** [comment]
> @luqmana That's already in stlouis so it could be used today if desired.

Only issue might be for anyone using the default `helios-dev` pkg repo which wouldn't have those bits.

**Comment by jclulow** [comment]
I will get `helios-dev` switched over to `stlouis` next week and then we won't have that problem anymore!
