### ISSUE TITLE
Should list project endpoint check for silo IAM role?

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#2676]
Now that organization is gone from the schema, the minimum IAM role a user needs to query projects is silo viewer. Without that, the person can only access their projects with the exact project name or id. This can be a pain if user had a typo when creating the project or somehow misremembered the project name.

If the silo admin has to grant silo viewer access to everyone, it is also not ideal because users are going to see all the projects in the silo when they may be authorized to just a handful of them (there are both privacy and usability concerns).

It's possible that we had a similar issue back when orgs were there, i.e. the unprivileged user or IdP user `bob` got a 403 for list orgs if we didn't explicitly grant the silo viewer role (though I don't remember having to do that, nor seeing all the orgs when logging in as `bob`). I did have to grant the org viewer role to users explicitly for them to list projects in the org. Now that project has become a root-level object, if what I mentioned above is correct, then `/v1/projects` should return projects of which the login user is a member (i.e. by virtue of having any direct or group IAM role in the project).

**Comment by david-crespo** [comment]
I vaguely recall that the unprivileged user is unprivileged to an artificial extent, and the typical user is in fact planned to have silo viewer.

**Comment by askfongjojo** [comment]
Let me make a VM with a pre-V1 API to definitively tell what behavior has/hasn't changed.  The main concern here is the all-or-nothing project list. It's not so much about the need for silo-viewer permission after all. It may just be a side effect of org removal that makes an existing behavior less desirable.

**Comment by davepacheco** [comment]
There is some related discussion in #1354 (which is pre-removal-of-Organizations, but I think it mostly still applies).  I _think_ this behavior was true before but I'll be interested to see if it's changed.

On the question of all-or-nothing list APIs: this was a simplifying assumption we discussed a while ago (I think late 2021) -- namely, that listing is always all-or-nothing, not filtered to what you're authorized to use/see.  That was really done to limit scope for MVP, not because we thought it was better, but having looked at other products, I think it's possible that it's also a better user experience.  I've been assuming we would basically wait to see what feedback we get to prioritize the work to make this more fine-grained.  (I think it's not a small amount of work.)
