### ISSUE TITLE
Failed instances should be allowed to stop and restart

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/omicron#2825]
Currently Nexus accepts no attempts to change the state of a Failed instance: https://github.com/oxidecomputer/omicron/blob/ee0aac053f178980d0c2d0e6c40bea38688961f9/nexus/src/app/instance.rs#L395-L416

There are plenty of reasons an instance could move to the Failed state (e.g. a failure to start the VM in Propolis, a heartbeat failure like those discussed in #2727, etc.). A VM user needs to be able to stop and attempt to restart a failed instance.

(Note that, on the Propolis end, once an instance has failed, it can't be restarted--the Propolis zone needs to be destroyed and recreated.)

**Comment by askfongjojo** [comment]
One of the things I think will be helpful is to avoid automatically setting instance state to `Failed` when it doesn't fall into the normal lifecycle state transition. This is especially true when a VM instance is wiped during an unintended propolis zone clean-up (e.g. because of a sled-agent crash and restart, or an orderly shutdown of a sled for maintenance before instance migration can take place). This class of scenarios fit with the condition of a `stopped` instance because the propolis zone is already gone, unlike failed instances that are subject to the condition mentioned above, i.e.:

> on the Propolis end, once an instance has failed, it can't be restarted--the Propolis zone needs to be destroyed and recreated

**Comment by hawkw** [comment]
#6455 allowed failed instances to be restarted. I'm currently working on allowing them to be stopped as well.
