### ISSUE TITLE
RSS should be less trusting of arbitrary Sleds reached via Bootstrap Network

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#2952]
RSS currently uses the following to identify "peers that should be involved in the rack setup process":

https://github.com/oxidecomputer/omicron/blob/9f31e37445f6d94c7277550e8048f09f5db61179/sled-agent/src/rack_setup/service.rs#L948-L951

This function simply waits for "enough peers to show up" before proceeding with subsequent stages of RSS (provisioning portions of the underlay, starting sled agents, provisioning resources, etc). It does not currently validate "who these peers are" - our expectation was that this would eventually be performed via trust quorum when we establish a shared secret.

From @rmustacc in chat:

> Software needs to be built assuming, eventually that arbitrary things that are hostile are on that network.
> If the issue is just assuming that because I can talk to someone on the bootstrap network rss should use it, then that's a bug imho.

This issue is currently impacting environments where "multiple instantiations of Omicron are deployed on the same rack", such as the testing that we're performing on rack2. 

What needs to be done:
- [ ] RSS needs a way to confirm that the sleds that it can see on the bootstrap network are ones that it *should* be talking to. Previously I thought this would be done via the trust quorum, but it could also be confirmed manually, or via a configuration file.

**Comment by rmustacc** [comment]
Regarding the trust quorum, the way to think about this is at some point you need to select nodes that you want to operate on. During setup time, someone needs to input that selection. As a side effect of that one will establish a trust quorum with those nodes; however, even absent that you can still use that selection process as a part of knowing who or what to talk to. When performing initial set up we still need to select those nodes. While usually it will be everything, when we do an initial deployment there may be hardware or other issues that leave the nodes operable (so we can deliver a software update or other fix in the future), but not want to be part of that.

One way to approach this is that when performing setup and getting the general set of information that we expect from wicketd, we just require that list be given to us. If you want to ease developer experience an option here (not sure if this makes sense) is to make it so if wicket/wicketd (or someone manually) don't include a list of systems in the request to RSS, it is only the single sled (which I say because IIUC RSS is not a separate actor, but rather just a part of sled agent).
