### ISSUE TITLE
Initial time sync stuck if external connectivity not initially available.

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/omicron#3137]
I started a cluster and did not get around to enabling external connectivity for a while as I was debugging other things. When I had sorted out the other things I was working on, I noticed time synchronization was not converging. With messages like this in the sled-agent logs

```
04:22:14.414Z WARN SledAgent (RSS): Time is not yet synchronized
    error = "Time is synchronized on 2/12 sleds"
```

But the 2/12 not making any progress.

I was able to eventually get past this by restarting all the ntp services and then things synced up.

```
pilot host exec -c "zlogin oxz_ntp svcadm restart ntp" 8 10 11 12 13 16 17 19 21 23 24 26 28
```

**Comment by citrus-it** [comment]
We saw something similar during one of the dogfood bringups last week, where there did not seem to be any progress after 9/12 reaching synchronisation. I captured the output of `chronyc tracking` from the `oxz_ntp` zone on one of the sleds that was not synchronised and it looked like this:

```
Reference ID    : 63B5BBCD (fd00:1122:3344:106::13)
Stratum         : 4
Ref time (UTC)  : Tue May 23 16:36:21 2023
System time     : 1148742528.000000000 seconds slow of NTP time
Last offset     : -0.000000879 seconds
RMS offset      : 0.159544259 seconds
Frequency       : 51.831 ppm slow
Residual freq   : -0.001 ppm
Skew            : 0.135 ppm
Root delay      : 0.060256962 seconds
Root dispersion : 0.001352694 seconds
Update interval : 16.1 seconds
Leap status     : Normal
```

The three apparently stuck zones had their `ntp` services restarted and immediately came into sync and RSS was able to continue, we do not know if they would have become synchronised by themselves but it is possible that they are beyond the time at which their configuration allows them to do a step time adjustment. 

We should:
- Configure more logging from chrony so that we can get a better understanding of what is happening;
- If time allows, wait and see what happens to one of the servers in this state;
- Review the chrony configuration around step synchronisation.

**Comment by citrus-it** [comment]
I believe this is happening because the boundary NTP servers are configured to enable *local reference mode*, which makes it act as an authoritative server  **even when it was never synchronised**.

In this case, the non-boundary servers will think they have reached synchronisation at January 1987, and when the boundary server gets connectivity and steps the clock forward to today, the non-boundary servers will slew the clock rather than step it as they are past their configured update threshold - they will only step the clock during the first three time updates after start.
