### ISSUE TITLE
Want stable PCI slot assignments for disks (to avoid invalidating boot order on disk attach/detach)

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#3224]
I couldn't replicate this issue consistently but this is the instance which I ran into such an issue.

Order of events:
1. Created instance with two disks - disk0: Ubuntu focal, disk1: blank disk
2. After starting the vm, formatted and mounted disk1
```
ubuntu@focal3:~$ lsblk
NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0          7:0    0 91.9M  1 loop /snap/lxd/24061
loop1          7:1    0 63.3M  1 loop /snap/core20/1822
loop2          7:2    0 49.9M  1 loop /snap/snapd/18357
vda          252:0    0   21K  1 disk 
nvme0n1      259:0    0    3G  0 disk 
├─nvme0n1p1  259:2    0  2.9G  0 part /
├─nvme0n1p14 259:3    0    4M  0 part 
└─nvme0n1p15 259:4    0  106M  0 part /boot/efi
nvme1n1      259:1    0   30G  0 disk /data
```
3. Stopped vm. Added 2 more blank disks (disk2 and disk3) via the console which invoked the disk attach API. Started vm again:
```
ubuntu@focal3:~$ lsblk
NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0          7:0    0 63.3M  1 loop /snap/core20/1822
loop1          7:1    0 63.3M  1 loop /snap/core20/1879
loop2          7:2    0 91.9M  1 loop /snap/lxd/24061
loop3          7:3    0 49.9M  1 loop /snap/snapd/18357
vda          252:0    0   21K  1 disk 
nvme0n1      259:0    0   30G  0 disk 
nvme1n1      259:1    0   30G  0 disk 
nvme2n1      259:2    0    3G  0 disk 
├─nvme2n1p1  259:3    0  2.9G  0 part /
├─nvme2n1p14 259:4    0    4M  0 part 
└─nvme2n1p15 259:5    0  106M  0 part /boot/efi
nvme3n1      259:6    0   30G  0 disk /data4096
```
I noticed the boot disk changed from `nvme0n1` to `nvme2n1`. Assuming that `nvme3n1` was one of the newly attached disks, I tried to format it but then found that it was actually disk1 (i.e. the device previously named `nvme1n1`)
```
ubuntu@focal3:~$ sudo mkfs -t ext4 /dev/nvme3n1
mke2fs 1.45.5 (07-Jan-2020)
/dev/nvme3n1 contains a ext4 file system
	last mounted on /data on Sat May  6 04:57:54 2023
Proceed anyway? (y,N) N
```
4. Stopped vm again. Removed disk1 via console. Started vm again and it stayed in `starting` state forever, presumably because it used the incorrect disk to boot?

**Comment by gjcolombo** [comment]
The relevant bit of Nexus is here: https://github.com/oxidecomputer/omicron/blob/abfca0b50430593f9aca90902c75f3a3297130c2/nexus/src/app/instance.rs#L623-L636

The disk request has room for a PCI slot, but the slot selection is determined from the disk enumeration order and not from an assignment in CRDB. We should assign slots for disks instead. I think there are DB helpers to do this for NICs, so there's probably a lot of code we can borrow to do that.

**Comment by gjcolombo** [comment]
@zephraph, @ahl, and I discussed this today. Because this issue... materially reduces the utility of the disk attach/detach APIs, to the point where if we don't fix it we might not be able comfortably to expose those APIs at FCS, we're planning to move it to that milestone.

To fix this specific problem we need to do the following:

- [ ] Add a `slot` column to the `disks` table in CRDB; this is probably going to be a nullable integer that can take values from 0-7 inclusive
- [ ] Construct a disk attachment query that uses the `NextItem` helper in `nexus::db_queries` to select a slot for a disk when attaching it. There's precedent here in the existing queries for network interfaces; the general idea is to construct a CTE with a WHERE clause with the semantics "given an instance ID, return the lowest slot number for which there is no disk attached to the instance that has been assigned that slot number" and then write that into the `slot` column when updating the disk's attachment state.
- [ ] Add similar logic to clear the `slot` assignment when a disk is detached.
- [ ] Fix the `disk_reqs` construction logic in the previous comment to populate `DiskRequest::slot` from the checked-out volume record instead of from the index supplied by `enumerate`.

No Propolis changes should be required here--once the slot in the `DiskRequest` is populated consistently, Propolis should take care of the rest.

In addition to the work above, we'd like to change the instance create API so that one of the disks is labeled as the "preferred boot disk." The instance create saga would then ensure that this disk is always attached first so that it ends up in slot 0. If the disk is bootable and my reading of the EDK2 code is correct (see above), this will cause its boot application to be chosen before the boot applications on any other attached bootable disks. We'll file a separate issue for this.

In the longer term (MVP or even later), we can also consider supporting the QEMU fw_cfg bootorder interface. I'll capture that idea into a short RFD when I have a moment of free time and inspiration.

**Comment by bnaecker** [comment]
@gjcolombo I'm familiar with the `NextItem` query and its use in the NIC allocation stuff, so don't hesitate to give a shout if I can help on that bit of this!

**Comment by gjcolombo** [comment]
I've looked at this in a little more detail. The `NextItem` subquery mechanics make sense to me in general. The challenge is working out whether we can use them more or less as-is in the ["attach to collection" CTE](https://github.com/oxidecomputer/omicron/blob/main/nexus/db-queries/src/db/collection_attach.rs). I don't currently see an easy way to do that. If that's correct, I think we'll have to do one of the following:

1. Restructure the "attach to collection" CTE to allow it to function more like the NIC attachment queries while maintaining its generic "attaching X to container Y" character. This would entail allowing callers to supply a subquery similar to the interface validation CTE (see `push_interface_validation_cte`) and then giving them a way to refer to it in the generic update statement (see the `select_from_cte` helper routine).
2. Abandon the generic collection-attachment CTE and hand-roll the necessary CTEs for disks.

Approach #1 might let us unify some disk and network interface code (and could possibly be reused in the future if we have other kinds of resources we want to attach), but it seems like a lot more work than approach #2, if it's even feasible at all (I would rate my Diesel skills at about a 2 out of 10, just enough to know that I have no idea whether this could actually work). I also wonder if YAGNI applies here--there just aren't that many kinds of resources that we attach to other resources this way; is the juice of a highly-configurable, very generic attachment mechanism worth the squeeze given how few resources we try to pair up this way?

**Comment by gjcolombo** [comment]
I think I've found a way forward here that lets us use the existing `NextItem` logic alongside the existing `DatastoreAttachTarget` logic (it turns out to be relatively straightforward to handcraft the `SET` clause of the `UPDATE` statement in the disk attach CTE so that the SET can leverage `NextItem`). The resulting change is not quite done (needs more tests and has some TODOs), but I should be able to get it mostly polished up and posted to GH tomorrow before I go OOO next week.

Here's a sample `debug_query` dump of the queries the new code is generating; this at least looks like what I intended, and the basic instance creation saga test passes with it:

```
"WITH collection_by_id AS 
(SELECT \"instance\".\"id\",
	\"instance\".\"name\",
	\"instance\".\"description\",
	\"instance\".\"time_created\",
	\"instance\".\"time_modified\",
	\"instance\".\"time_deleted\",
	\"instance\".\"project_id\",
	\"instance\".\"user_data\",
	\"instance\".\"state\",
	\"instance\".\"time_state_updated\",
	\"instance\".\"state_generation\",
	\"instance\".\"active_sled_id\",
	\"instance\".\"active_propolis_id\",
	\"instance\".\"active_propolis_ip\",
	\"instance\".\"target_propolis_id\",
	\"instance\".\"migration_id\",
	\"instance\".\"propolis_generation\",
	\"instance\".\"ncpus\",
	\"instance\".\"memory\",
	\"instance\".\"hostname\"
	FROM \"instance\"
	WHERE ((\"instance\".\"id\" = $1) AND
              (\"instance\".\"time_deleted\" IS NULL)) FOR UPDATE),
resource_by_id AS
(SELECT \"disk\".\"id\",
  	\"disk\".\"name\",
	\"disk\".\"description\",
	\"disk\".\"time_created\",
	\"disk\".\"time_modified\",
	\"disk\".\"time_deleted\",
	\"disk\".\"rcgen\",
 	\"disk\".\"project_id\",
	\"disk\".\"volume_id\",
	\"disk\".\"disk_state\",
	\"disk\".\"attach_instance_id\",
	\"disk\".\"state_generation\",
	\"disk\".\"time_state_updated\",
	\"disk\".\"slot\",
	\"disk\".\"size_bytes\",
	\"disk\".\"block_size\",
	\"disk\".\"origin_snapshot\",
	\"disk\".\"origin_image\",
	\"disk\".\"pantry_address\"
	FROM \"disk\"
	WHERE ((\"disk\".\"id\" = $2) AND
	      (\"disk\".\"time_deleted\" IS NULL)) FOR UPDATE),
resource_count AS
(SELECT COUNT(*)
 FROM \"disk\"
 WHERE ((\"disk\".\"attach_instance_id\" = $3) AND (\"disk\".\"time_deleted\" IS NULL))),
collection_info AS
(SELECT \"instance\".\"id\",
	\"instance\".\"name\",
	\"instance\".\"description\",
	\"instance\".\"time_created\",
	\"instance\".\"time_modified\",
	\"instance\".\"time_deleted\",
	\"instance\".\"project_id\",
	\"instance\".\"user_data\",
	\"instance\".\"state\",
	\"instance\".\"time_state_updated\",
	\"instance\".\"state_generation\",
	\"instance\".\"active_sled_id\",
	\"instance\".\"active_propolis_id\",
	\"instance\".\"active_propolis_ip\",
	\"instance\".\"target_propolis_id\",
	\"instance\".\"migration_id\",
	\"instance\".\"propolis_generation\",
	\"instance\".\"ncpus\",
	\"instance\".\"memory\",
	\"instance\".\"hostname\"
	FROM \"instance\"
	WHERE (((\"instance\".\"state\" = ANY($4)) AND
	      (\"instance\".\"id\" = $5)) AND
	      (\"instance\".\"time_deleted\" IS NULL)) FOR UPDATE),
resource_info AS
(SELECT \"disk\".\"id\",
	\"disk\".\"name\",
	\"disk\".\"description\",
	\"disk\".\"time_created\",
	\"disk\".\"time_modified\",
	\"disk\".\"time_deleted\",
	\"disk\".\"rcgen\",
	\"disk\".\"project_id\",
	\"disk\".\"volume_id\",
	\"disk\".\"disk_state\",
	\"disk\".\"attach_instance_id\",
	\"disk\".\"state_generation\",
	\"disk\".\"time_state_updated\",
	\"disk\".\"slot\",
	\"disk\".\"size_bytes\",
	\"disk\".\"block_size\",
	\"disk\".\"origin_snapshot\",
	\"disk\".\"origin_image\",
	\"disk\".\"pantry_address\"
	FROM \"disk\"
	WHERE ((((\"disk\".\"disk_state\" = ANY($6)) AND
	      (\"disk\".\"id\" = $7)) AND
	      (\"disk\".\"time_deleted\" IS NULL)) AND
	      (\"disk\".\"attach_instance_id\" IS NULL)) FOR UPDATE),
do_update AS
(SELECT IF(EXISTS(SELECT \"id\" FROM collection_info) AND
           EXISTS(SELECT \"id\" FROM resource_info) AND
	   (SELECT * FROM resource_count) < 8, TRUE, FALSE)),
updated_resource AS
(UPDATE \"disk\" SET \"attach_instance_id\" = $8,
		     \"disk_state\" = $9,
		     \"slot\" = (SELECT $10 + \"shift\" AS \"slot\" FROM 
		     		(SELECT generate_series(0, $11) AS \"shift\"
				UNION ALL SELECT generate_series($12, -1) AS \"shift\")
				LEFT OUTER JOIN \"disk\"
				ON (\"attach_instance_id\", \"slot\", \"time_deleted\" IS NULL) = 
				   ($13, $14 + \"shift\", TRUE)
				WHERE \"slot\" IS NULL
				LIMIT 1)
WHERE (\"disk\".\"id\" = $15)
AND (SELECT * FROM do_update)
RETURNING \"disk\".\"id\",
	  \"disk\".\"name\",
	  \"disk\".\"description\",
	  \"disk\".\"time_created\",
	  \"disk\".\"time_modified\",
	  \"disk\".\"time_deleted\",
	  \"disk\".\"rcgen\",
	  \"disk\".\"project_id\",
	  \"disk\".\"volume_id\",
	  \"disk\".\"disk_state\",
	  \"disk\".\"attach_instance_id\",
	  \"disk\".\"state_generation\",
	  \"disk\".\"time_state_updated\",
	  \"disk\".\"slot\",
	  \"disk\".\"size_bytes\",
	  \"disk\".\"block_size\",
	  \"disk\".\"origin_snapshot\",
	  \"disk\".\"origin_image\",
	  \"disk\".\"pantry_address\")
SELECT * FROM 
	(SELECT * FROM resource_count) LEFT JOIN
	(SELECT * FROM collection_by_id) ON TRUE LEFT JOIN
	(SELECT * FROM resource_by_id) ON TRUE LEFT JOIN
	(SELECT * FROM updated_resource) ON TRUE;",

    binds: [
    	// $1: instance ID
        66894238-988f-4ab1-aa85-4cb44a0c94f7,
	// $2: disk ID
        aa1d8ae3-dc72-4c78-a94d-5c013d1034f0,
	// $3: instance ID
        66894238-988f-4ab1-aa85-4cb44a0c94f7,
	// $4: valid instance states for attach
        [
            InstanceState(
                Creating,
            ),
            InstanceState(
                Stopped,
            ),
        ],
	// $5: instance ID
        66894238-988f-4ab1-aa85-4cb44a0c94f7,
	// $6: valid disk states for attach
        [
            "creating",
            "detached",
        ],
	// $7: disk ID
        aa1d8ae3-dc72-4c78-a94d-5c013d1034f0,
	// $8: attach instance ID to set
        66894238-988f-4ab1-aa85-4cb44a0c94f7,
	// $9: disk state to set
        "attached",
	// $10: shift base
        0,
	// $11: shift max
        8,
	// $12: shift min
        0,
	// $13: expected attach instance ID
        66894238-988f-4ab1-aa85-4cb44a0c94f7,
	// $14: shift base
        0,
	// $15: disk ID
        aa1d8ae3-dc72-4c78-a94d-5c013d1034f0,
    ],
```
