### ISSUE TITLE
nexus mysteriously reports 404 for destroyed instance

### ISSUE THREAD

**Issue by jordanhendricks** [oxidecomputer/omicron#3231]
On rack2, we noticed that a sled-agent was repeatedly complaining that it was getting a 404 trying to report instance state to nexus:
```
00:42:28.304Z WARN SledAgent (InstanceManager): Failed to publish instance state to Nexus: Notifying Nexus failed: Error Response: status: 404 Not Found; headers: {"content-type": "application/json", "x-request-id": "c3e85d6a-b183-4224-ac46-d07917e58a0d", "content-length": "177", "date": "Fri, 26 May 2023 00:42:28 GMT"}; value: Error { error_code: Some("ObjectNotFound"), message: "not found: instance with id \"44eb4304-08a5-40a5-85f6-4ac206c5be01\"", request_id: "c3e85d6a-b183-4224-ac46-d07917e58a0d" }
    instance_id = 44eb4304-08a5-40a5-85f6-4ac206c5be01
    retry_after = 809.947502ms
```

An important bit of context is that this instance was created before nexus crashed on rack2 due to a saga unwind panic. Nexus was recovered with this [procedure](https://github.com/oxidecomputer/meta/blob/master/engineering/dogfood.adoc#102-manually-setting-a-saga-to-done), and this failure happened afterward. (At this time, I am not certain if this was the specific instance that caused nexus to crash.)

If we check the nexus logs for that request ID, we see:
```
root@oxz_nexus:~# grep c3e85d6a-b183-4224-ac46-d07917e58a0d $(svcs -L nexus) | looker
00:42:28.302Z DEBG 2715a57f-bcc6-464d-8fe2-6fa967a289f9 (dropshot_internal): roles
    actor_id = 001de000-05e4-4000-8000-000000000002
    authenticated = true
    local_addr = [fd00:1122:3344:109::4]:12221
    method = PUT
    remote_addr = [fd00:1122:3344:109::1]:48295
    req_id = c3e85d6a-b183-4224-ac46-d07917e58a0d
    roles = RoleSet { roles: {} }
    uri = /instances/44eb4304-08a5-40a5-85f6-4ac206c5be01
00:42:28.303Z DEBG 2715a57f-bcc6-464d-8fe2-6fa967a289f9 (dropshot_internal): authorize result
    action = Query
    actor = Some(Actor::UserBuiltin { user_builtin_id: 001de000-05e4-4000-8000-000000000002, .. })
    actor_id = 001de000-05e4-4000-8000-000000000002
    authenticated = true
    local_addr = [fd00:1122:3344:109::4]:12221
    method = PUT
    remote_addr = [fd00:1122:3344:109::1]:48295
    req_id = c3e85d6a-b183-4224-ac46-d07917e58a0d
    resource = Database
    result = Ok(())
    uri = /instances/44eb4304-08a5-40a5-85f6-4ac206c5be01
00:42:28.304Z INFO 2715a57f-bcc6-464d-8fe2-6fa967a289f9 (dropshot_internal): request completed
    error_message_external = not found: instance with id "44eb4304-08a5-40a5-85f6-4ac206c5be01"
    error_message_internal = not found: instance with id "44eb4304-08a5-40a5-85f6-4ac206c5be01"
    local_addr = [fd00:1122:3344:109::4]:12221
    method = PUT
    remote_addr = [fd00:1122:3344:109::1]:48295
    req_id = c3e85d6a-b183-4224-ac46-d07917e58a0d
    response_code = 404
    uri = /instances/44eb4304-08a5-40a5-85f6-4ac206c5be01
```

Just before that, we see these log lines:
```
00:42:28.302Z INFO 2715a57f-bcc6-464d-8fe2-6fa967a289f9 (dropshot_internal): accepted connection
    local_addr = [fd00:1122:3344:109::4]:12221
    remote_addr = [fd00:1122:3344:109::1]:48295
00:42:28.302Z DEBG 2715a57f-bcc6-464d-8fe2-6fa967a289f9 (ServerContext): received new runtime state from sled agent
    instance_id = 44eb4304-08a5-40a5-85f6-4ac206c5be01
    runtime_state = InstanceRuntimeState { run_state: Stopped, sled_id: d2832cf3-0e38-4452-b59f-b926ad665306, propolis_id: 67c0b428-d198-4397-9354-be5e8fdc6936, dst_propolis_id: None, propolis_addr: Some([fd00:1122:3344:109::22]:12400), migration_id: None, propolis_gen: Generation(2), ncpus: InstanceCpuCount(32), memory: ByteCount(68719476736), hostname: "ekkke", gen: Generation(8), time_updated: 2023-05-25T21:16:51.321064765Z }
```

It seems that nexus is reporting that it can't find the instance sled-agent is asking to update.

That instance is destroyed, and in CRDB:
```
root@[fd00:1122:3344:109::6]:32221/omicron> select * from instance where id = '44eb4304-08a5-40a5-85f6-4ac206c5be01';
                   id                  | name  |   description    |         time_created          |         time_modified         |         time_deleted          |              project_id              | user_data |   state   |      time_state_updated       | state_generation |            active_sled_id            |          active_propolis_id          |   active_propolis_ip   | target_propolis_id | migration_id | propolis_generation | ncpus |   memory    | hostname
---------------------------------------+-------+------------------+-------------------------------+-------------------------------+-------------------------------+--------------------------------------+-----------+-----------+-------------------------------+------------------+--------------------------------------+--------------------------------------+------------------------+--------------------+--------------+---------------------+-------+-------------+-----------
  44eb4304-08a5-40a5-85f6-4ac206c5be01 | ekkke | Ptang Zoo Boing! | 2023-05-25 21:15:56.833785+00 | 2023-05-25 21:15:56.833785+00 | 2023-05-25 21:16:47.825445+00 | e2460b2b-8a90-471f-aa7c-88f4af360c68 |           | destroyed | 2023-05-25 21:16:41.966097+00 |                7 | d2832cf3-0e38-4452-b59f-b926ad665306 | 67c0b428-d198-4397-9354-be5e8fdc6936 | fd00:1122:3344:109::22 | NULL               | NULL         |                   1 |    32 | 68719476736 | ekkke
(1 row)
```

This is the sled it's on (coincidentally the same as the one CRDB is on):
```
root@[fd00:1122:3344:109::6]:32221/omicron> select * from sled where id = 'd2832cf3-0e38-4452-b59f-b926ad665306';
                   id                  |         time_created          |         time_modified         | time_deleted | rcgen |               rack_id                | is_scrimlet | serial_number | part_number | revision | usable_hardware_threads | usable_physical_ram |          ip           | port  |   last_used_address
---------------------------------------+-------------------------------+-------------------------------+--------------+-------+--------------------------------------+-------------+---------------+-------------+----------+-------------------------+---------------------+-----------------------+-------+-------------------------
  d2832cf3-0e38-4452-b59f-b926ad665306 | 2023-05-25 20:29:53.469654+00 | 2023-05-25 20:29:53.473515+00 | NULL         |    31 | 2790c435-719b-4569-ae5a-15cba3850bb0 |    true     | BRM42220014   | 913-0000019 |        6 |                     128 |       1086608900096 | fd00:1122:3344:109::1 | 12345 | fd00:1122:3344:109::25
```

This log line from nexus:
```
00:42:28.302Z DEBG 2715a57f-bcc6-464d-8fe2-6fa967a289f9 (ServerContext): received new runtime state from sled agent
    instance_id = 44eb4304-08a5-40a5-85f6-4ac206c5be01
    runtime_state = InstanceRuntimeState { run_state: Stopped, sled_id: d2832cf3-0e38-4452-b59f-b926ad665306, propolis_id: 67c0b428-d198-4397-9354-be5e8fdc6936, dst_propolis_id: None, propolis_addr: Some([fd00:1122:3344:109::22]:12400), migration_id: None, propolis_gen: Generation(2), ncpus: InstanceCpuCount(32), memory: ByteCount(68719476736), hostname: "ekkke", gen: Generation(8), time_updated: 2023-05-25T21:16:51.321064765Z }
```

comes from the beginning of [notify_instance_updated](https://github.com/oxidecomputer/omicron/blob/35a5ed78a836b43c86d563025f20f6c9accd0041/nexus/src/app/instance.rs#L1003-L1005).

A couple things to note: sled agent is reporting a higher generation number for both the regular generation number (8) and the propolis ID generation number (2) than what is in the database. CRDB has 7 and 1, respectively. But this is expected to work based on our rules about updates based on generation numbers, and an inspection of the code indicates to me that we do this.

The strange thing is that we don't see anything else logged from nexus indicating why it thought the instance didn't exist. We would expect to see the [result of instance_update_runtime](https://github.com/oxidecomputer/omicron/blob/35a5ed78a836b43c86d563025f20f6c9accd0041/nexus/src/app/instance.rs#L1055-L1098) log something, presumably the `Error::ObjectNotFound` case, but we don't. We also see that the auth succeeds, and nothing is logged from [handle_instance_propolis_gen_change](https://github.com/oxidecomputer/omicron/blob/35a5ed78a836b43c86d563025f20f6c9accd0041/nexus/src/app/instance.rs#L1109-L1113).

@bnaecker was also watching for incoming queries to CRDB with dtrace the whole time, and only ever observed a `select` queries, not `updates` for this instance.

So where did nexus get the 404 from?

**Comment by jordanhendricks** [comment]
It seems that #3230 is at play here. As that issue notes, `time_deleted` on this instance is not NULL, so the record of the instance is deleted.

But I'm still confused why we don't see any log messages from nexus indicating what happened.

**Comment by jordanhendricks** [comment]
Nexus log is at: /net/catacomb/data/staff/core/rack2/omicron-3231

**Comment by bnaecker** [comment]
I think the lack of logs is explained by the database query. If we look at the query itself either with DTrace or inspecting the query generation code, there’s a condition filtering out those records with non-NULL time deleted. So nexus really does think there’s no such instance because it’s been deleted earlier, and so it returns the 404.

**Comment by jordanhendricks** [comment]
@bnaecker this made me wonder why nexus would log the `Error::ObjectNotFound` case at all, then I noticed there was a comment there I missed that wondered the same thing:

https://github.com/oxidecomputer/omicron/blob/35a5ed78a836b43c86d563025f20f6c9accd0041/nexus/src/app/instance.rs#L1072-L1083

**Comment by bnaecker** [comment]
So I believe we never get here, and possibly that this comment is out of date. The query we're issuing in the instance lookup, as seen via DTrace, is:

```
112  12770 _ZN95_$LT$diesel_dtrace..DTraceConnection$LT$C$GT$$u20$as$u20$diesel..connection..LoadConnection$GT$4load17h0ee1f5d4efd496f9E:query-start SELECT "instance"."id", "instance"."name", "instance"."description", "instance"."time_created", "instance"."time_modified", "instance"."time_deleted", "instance"."project_id", "instance"."user_data", "instance"."state", "instance"."time_state_updated", "instance"."state_generation", "instance"."active_sled_id", "instance"."active_propolis_id", "instance"."active_propolis_ip", "instance"."target_propolis_id", "instance"."migration_id", "instance"."propolis_generation", "instance"."ncpus", "instance"."memory", "instance"."hostname" FROM "instance" WHERE (("instance"."time_deleted" IS NULL) AND ("instance"."id" = $1)) -- binds: [44eb4304-08a5-40a5-85f6-4ac206c5be01]
```

So the `WHERE time_deleted IS NULL` means we get back zero records. I believe we're returning the not-found error from here:

https://github.com/oxidecomputer/omicron/blob/35a5ed78a836b43c86d563025f20f6c9accd0041/nexus/src/app/instance.rs#L1035-L1038

That is consistent with the aspects that we were very confused by initially, such as that we don't see any log statements inside the call to `handle_instance_propolis_gen_change` or `instance_update_runtime`. We're returning before that, because the lookup method returned an `Err`.

To be clear, I can't prove that yet, it's just consistent with all the logs we (don't) see and what I'd expect the DB query we do issue to return, namely zero records.

**Comment by gjcolombo** [comment]
@bnaecker: I think your analysis is right. I'm able to repro the 404 by stopping an instance and then immediately deleting it as soon as the stop request returns. It's not a 100% repro, but with a large enough instance the odds are decent that the delete call will land while Propolis thinks the instance is Stopped but not yet Destroyed; if that happens, the transition to Destroyed will produce the call to `notify_instance_updated` that immediately 404s.

The initial query in `notify_instance_updated` is relatively new. It's there so that this function can try to assess whether an instance has moved between sleds and update configuration and/or release unused Propolis reservations if it has. I agree that this change mostly obsoletes the comment about swallowing failures to update due to a not-found error; I'll think about how to reword that. (In the longer run, there are probably better ways to ensure that the rack's networking configuration is up-to-date than to try to rely on updating it inline in the state update path; for example, it might be better to publish state updates and then try to address their consequences in a background task. But this was a less expensive way to try to unblock additional migration work.)

In any case, sled agent should handle *all* kinds of errors from this function more gracefully; I'm mostly tracking that through #3230, for which I hope to have a fix drafted first thing next week.
