### ISSUE TITLE
Launching a mega instance kills neighbors

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/omicron#3286]
On Rack2 an instance with 32 VCPUs and 128G of memory failed and took out neighboring instances with it. The large instance in question here is the `yolo-bigger-debian-cloud-77e4ec` instance. Sled agent log attached.

[large-instance-crash.log](https://github.com/oxidecomputer/omicron/files/11639324/large-instance-crash.log)

**Comment by rcgoodfellow** [comment]
Looks like clobbering neighbors may be due to #2646

**Comment by askfongjojo** [comment]
The validation / error handling can be in the control plane or hypervisor. I'm going to raise this with the hypervisor team to understand our strategy for handling this class of issues.
cc @pfmooney , @zephraph

**Comment by askfongjojo** [comment]
Per discussions at the hypervisor huddle, the validations of maximum vcpu/memory should be in sled-agent or propolis since they are versioned/updated together. Putting them in the API will introduce the need for synchronization when the limits are changed in the future.

We also do not understand why provisioning a 32 vcpu 128Gb-memory VM should fail since this isn't a bhyve limitation. We'll need to replicate the issue and watch the propolis log before it gets deleted. This can be done more easily on a standalone sled (as opposed to an entire rack which have many sleds).

**Comment by askfongjojo** [comment]
Will apply the API guardrail as noted in https://github.com/oxidecomputer/omicron/issues/3212. (I'm not changing the assignment since it still has to be fixed with VMM reservoir.)

**Comment by zephraph** [comment]
The mitigations for all of this should be in place now. The caps are implemented in the Nexus app layer instead of pushed down into sled-agent or propolis as suggested, so there's likely future follow up work here to change around where the check happens.

**Comment by askfongjojo** [comment]
Besides the mitigation, the long-term fixes for the two issues concerned are tracked under #3417 and #2646. We can mark this one closed.
