### ISSUE TITLE
Remove "spoof" authn scheme from configuration files

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#372]
To be able to continue accessing Nexus' endpoints, configuration files must use the `spoof` authn scheme.

This issue tracks removal of that scheme (we don't want to ship with it!) when we have a reasonable replacement.

**Comment by davepacheco** [comment]
I do think it would be a lot safer to remove support altogether (and that was the original intent).  We have enough pieces now (or almost do) to be able to do this, I think.

**Comment by davepacheco** [comment]
Removing "spoof" probably depends on #2304 because otherwise you'd have no way to make any requests to the API to bootstrap yourself to a user with a password.  But once we've done #2304, any real or simulated system should be able to use a real, ordinary user with a password to log in.  Only the test suite will still need "spoof".

With #2305, the test suite will be in charge of creating these users and can create them with a password and use that.  Or it can create a device access token for them and use that.  Either way, "spoof" shouldn't be needed.  I wouldn't try to remove "spoof" before we do #2305 because it seems like a bunch of extra work.
