### ISSUE TITLE
Failed to abandon contract -1 for pid

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#3828]
While testing #3827 on madrid, I noticed this in the sled-agent logs:

```
00:19:06.847Z ERRO SledAgent (ServiceManager): Failed to abandon contract -1 for pid 2389: Error opening file /proc/1467/contracts/-1/ctl: No such fil
e or directory (os error 2)
    file = illumos-utils/src/running_zone.rs:413
    zone = oxz_switch
00:19:07.270Z ERRO SledAgent (ServiceManager): Failed to abandon contract -1 for pid 2392: Error opening file /proc/1467/contracts/-1/ctl: No such fil
e or directory (os error 2)
    file = illumos-utils/src/running_zone.rs:413
    zone = oxz_switch
00:19:07.660Z ERRO SledAgent (ServiceManager): Failed to abandon contract -1 for pid 2394: Error opening file /proc/1467/contracts/-1/ctl: No such fil
e or directory (os error 2)
    file = illumos-utils/src/running_zone.rs:413
    zone = oxz_switch
00:19:08.092Z ERRO SledAgent (ServiceManager): Failed to abandon contract -1 for pid 2399: Error opening file /proc/1467/contracts/-1/ctl: No such fil
e or directory (os error 2)
    file = illumos-utils/src/running_zone.rs:413
    zone = oxz_switch
```

I don't _think_ any changes on #3827 would have impacted contracts. I haven't yet been able to dig into this (e.g., do these logs show up on the dogfood rack too and we haven't noticed?), but wanted to note it.

**Comment by citrus-it** [comment]
I see four instances of this log message on gc16 in dogfood too. There are far more than four commands invoked in a child zone during rack init so I wonder what is special about these four, and are they the same as the ones seen on Madrid?

```
BRM42220014 # grep -h 'Failed to abandon contract' /pool/ext/*/crypt/debug/global/*sled-agent* | looker
00:01:44.692Z ERRO SledAgent (BootstrapAgent): Failed to abandon contract -1 for pid 1591: Error opening file /proc/654/contracts/-1/ctl: No such file or directory (os error 2)
    file = illumos-utils/src/running_zone.rs:413
    zone = oxz_switch
00:01:45.110Z ERRO SledAgent (BootstrapAgent): Failed to abandon contract -1 for pid 1594: Error opening file /proc/654/contracts/-1/ctl: No such file or directory (os error 2)
    file = illumos-utils/src/running_zone.rs:413
    zone = oxz_switch
00:01:45.563Z ERRO SledAgent (BootstrapAgent): Failed to abandon contract -1 for pid 1599: Error opening file /proc/654/contracts/-1/ctl: No such file or directory (os error 2)
    file = illumos-utils/src/running_zone.rs:413
    zone = oxz_switch
00:01:46.066Z ERRO SledAgent (BootstrapAgent): Failed to abandon contract -1 for pid 1602: Error opening file /proc/654/contracts/-1/ctl: No such file or directory (os error 2)
    file = illumos-utils/src/running_zone.rs:413
    zone = oxz_switch
```

**Comment by jclulow** [comment]
Glancing briefly at the code, it seems like `pr_contract` would be read as `-1` under some conditions:

```c
/*
 * Return information used by ps(1).
 */
void
prgetpsinfo(proc_t *p, psinfo_t *psp)
{
...
        if ((psp->pr_contract = PRCTID(p)) == 0)
                psp->pr_contract = -1;
...
```

```c
#define PRCTID(pp) \
        ((pp)->p_ct_process ? (pp)->p_ct_process->conp_contract.ct_id : 0)
```

I believe we only assign `p_ct_process` in two places:

- first, in `contract_process_fork()`, when we establish the child process during `fork()`
- second, in `contract_process_exit()`, where we set it to `NULL`; this is called during `proc_exit()`

It seems like maybe this particular process is sufficiently short-lived that it is exiting before we're able to open up its proc file and read `pr_contract`?  You should confirm that with some tracing probably.

I think there are a few things we could investigate here:

- iff you get `-1` when trying to read the contract, you know there is at least one leaked contract; we could trigger contract reaper at that moment: using `ct_pr_status_get_contracts()` to list any contracts that have been inherited by our own contract; there should be at least one _empty_ inherited contract that we could then reap
- the semantics of the `pr_contract` member after the process has exited: should the OS actually be preserving the contract ID that was in effect _while the process was active_?  This doesn't seem a totally unreasonable change: lots of IDs appear to be preserved after exit for inspection, such as the process group ID or parent process ID.  Otherwise, should we add a _new_ field to the structure that contains the ID that was in effect earlier, even though it is no longer in effect because the process has exited?

**Comment by citrus-it** [comment]
> It seems like maybe this particular process is sufficiently short-lived that it is exiting before we're able to open up its proc file and read `pr_contract`? You should confirm that with some tracing probably.

The code splits the creation of the child from the running of the process specifically so that we can grab the contract ID between the fork() and exec(), but something is not working as intended. Getting -1 does not appears to happen on the standalone bench gimlet I used originally, or in the two test runs I did this morning, but has been seen on both rack2 (6/10 sleds have seen it), and madrid, so it would fit with a race somewhere.
