### ISSUE TITLE
Need API and support in Omicron to replace a crucible downstairs.

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/omicron#3886]
Crucible upstairs supports replacement of a specific downstairs.
propolis-server support is in progress.
Once Propolis server supports it, we need to add that support in Omicron.

**Comment by leftwo** [comment]
The propolis issue is: https://github.com/oxidecomputer/propolis/issues/470

**Comment by leftwo** [comment]
A rough idea on how this could work:

* Decide it's time to replace a downstairs.
* Nexus SAGA begins:
*  Create the new single downstairs.
* Update disk/volume state to `Maintenance` or `Repair` or something indicating it is undergoing work.
   - If this finds a disk is not the correct state, then abort now.
* Get current VCR from database, 
    - Construct new VCR with a target replaced
    - Store new VCR.
    - Store old VCR in "previous VCR" slot.
 * Send new VCR to propolis-server
 * Wait for Propolis-server to tell us the new VCR was accepted.
 * Mark disk in database as `Repairing` or `Repair Underway` Or some such 2nd state.
 * Nexus SAGA ends
 
At this point, Nexus does nothing more, assuming the replacement is underway.
At some future time, the replacement will finish.

* Crucible Upstairs sends a message to Nexus (like the scrub is done message) telling it, this replacement has finished. 
* Nexus replacement complete SAGA starts
* Find the Volume, remove the "old" vcr
* Verify it is in the proper state.
* Update the disk in the database as "OK" or whatever the default state now is (attached, etc).
* SAGA ends

**Comment by leftwo** [comment]
Some links from @smklein during a vchat:
Sean Klein1:01 PM
https://github.com/oxidecomputer/omicron/pull/2797
Sean Klein1:02 PM
https://github.com/oxidecomputer/omicron/tree/main/nexus/src/app/background
Sean Klein1:18 PM
https://github.com/oxidecomputer/omicron/blob/main/schema/crdb/README.adoc
https://github.com/oxidecomputer/omicron/blob/main/schema/crdb/2.0.0/up.sql
https://github.com/oxidecomputer/omicron/blob/main/schema/crdb/dbinit.sql

**Comment by smklein** [comment]
Just chatted over meet about some of this, and I figured I'd write down some notes to summarize our discussion

## Problems with storing the old VCR / rollback

IMO storing an "old" VCR and rolling back to it is a risky operations -- the thing triggering downstairs replacement is often going to be physical disk / sled failures, so this may not actually be a viable option. This arguably gets worse in the case of "multiple concurrent failures", because we may try rolling back the VCR to a state where it's "definitely wrong, even though it was right a while ago".

**My two cents**: If we fail to perform a downstairs replacement for whatever reason, it would be safer to "roll back to a truthful VCR, even if the truth hurts". Specifically: If we have downstairs A, B, C, we try to replace A, the set of operations should be:

1. Nexus updates the VCR record for the virtual disk to say "A is undergoing repair, B and C are OK"
2. propolis-server tries applying the VCR
    a. If applying the VCR succeeds, we move on with life.
    b. If applying the VCR fails, Nexus can update the DB to say "A **needs** repair, B and C are OK".
    
This presents a more accurate view of the world, rather than unwinding back to "A, B, and C are OK", which may be false if e.g., the sled running upstairs A died.

(Also of note: We clearly need to have optimistic concurrency control around the VCR, because it's possible that "B" dies while we were trying to fix "A").

## Storing replacement on a per-downstairs granularity

I don't really have a strong opinion about whether or not we do this in the CRDB schema or within the VCR JSON blob, but we need to store "per-downstairs" states about whether or not:

- A downstairs is healthy
- A downstairs is in need of re-allocation and repair
- A downstairs is in the process of repair

All these states are distinct, all of these states are possible, and all of them can happen for each of the downstairs.

If we have a top-level state on the virtual disk to indicate that it's `repairing`, that's fine (might be useful for indexing purposes!) but it needs to be active if-and-only-if one of the downstairs is not in the "healthy" state.

## Source of truth being Nexus for the VCR

Just to summarize our discussion here: the intent is that the "source of truth" for a virtual disk is the nexus copy of the VCR, not "whatever happens to be stored in the propolis-server". This is critical, because it informs our decision to "update CRDB first, through Nexus, before sending a request to the propolis-server".

## "assuming the replacement is underway" implies that downstairs re-allocation should be a Reliable Persistent Workflow (RPW)

- In the case of cold boot, we cannot assume that a replacement is underway: something may need to re-trigger such an operation.
- Additionally, in the case where "Nexus notices that a physical disk is dead", we should be able to mark the downstairs as "gone" without blocking such an operation behind a re-allocation. (As we said in the call, it's silly to have an API that says "You can't mark this hardware failure right now because we can't provision something").

Therefore, it'll be useful to decouple the operations of "a downstairs needs to be repaired" from "a downstairs is re-allocated, and is in the process of repairing". This lends itself nicely to an RPW, because we can continually try to re-provision downstairs which have failed, even if that reallocation process fails partway through.

It also makes the case of "a sled has died" or "a physical disk has died" much simpler from a Nexus point-of-view:

- If a physical disk dies (or goes missing, or whatever), we can iterate over all Crucible downstairs residing on that physical disk
- For each of those downstairs, we can iterate over all virtual disks using it
- For each of those virtual disks, we can update the VCR to say "downstairs is gone, in need of repair"

**Separately**, the downstairs re-provisioning RPW can monitor for virtual disks that contains VCRs indicating "downstairs is gone, in need of repair"
- This RPW can try to perform the allocation (and retry later, in case of failure)
- The RPW can also re-trigger repairs which need to be restarted after a cold boot

**Comment by leftwo** [comment]
I think it makes sense to have the per-downstairs state for a volume be stored in the
CRDB and not inside the VCR.  The VCR can be for what is, and the CRDB state exists outside
of that. 

This allows for desired states to be represented outside the VCR, and a RPW task to come
along and take action.

**Comment by leftwo** [comment]
This issue requires both replacement for a SubVolume and a ReadOnlyParent.  These two will be
broken into different issues.

**Comment by leftwo** [comment]
read only downstairs replacement is now possible in crucible with https://github.com/oxidecomputer/omicron/issues/3886
being merged to main.

However, it will be a little different procedure to create a RO clone than what we do for regular upstairs replacement.

If you have a ROP that needs a downstairs replacement, Nexus needs to follow these rough steps:
* Create a region with the same dementions as the failing one.
* Pick a working downstairs target.
* Restart the newly created region with the "clone" subcommand, giving it the repair address of the working (but RO) downstairs target.
* Let the clone finish, the replacement downstairs will exit
* Restart the replacement downstairs in RO.
* Replace the ROP target that was bad with the IP:Port of the new replacement.

I realize there are a lot of details to work out here, but that's the general idea.

**Comment by leftwo** [comment]
https://github.com/oxidecomputer/omicron/issues/5333 For the ROP replacement
