### ISSUE TITLE
CmdError error messages should provide more information

### ISSUE THREAD

**Issue by papertigers** [oxidecomputer/omicron#4419]
While testing on a bench gimlet I ran into a version mismatch for what sled-agent was expecting vs what version helios was using.

```
{"msg":"Sending prefix to ddmd for advertisement","v":0,"name":"SledAgent","level":30,"time":"2023-11-02T21:04:18.748039834Z","hostname":"gimlet-sn06","pid":104370,"DdmAdminClient":"[::1]:8000","component":"BootstrapAgentStartup","file":"clients/ddm-admin-client/src/lib.rs:91","prefix":"Ipv6Prefix { addr: fdb0:e8ea:6a09:6c32::, len: 64 }"}
sled-agent: Failed to delete all XDE devices
[ Nov  2 21:04:18 Stopping because all processes in service exited. ]
[ Nov  2 21:04:18 Executing stop method (:kill). ]
[ Nov  2 21:04:18 Restarting too quickly, changing state to maintenance. ]
```

Looking at where that error comes from pointed me at:
```rust
    illumos_utils::opte::delete_all_xde_devices(&log)
        .map_err(StartError::DeleteXdeDevices)?;
```

If we manually truss sled-agent we can see the ioctl call fails.
```
/129:   ioctl(3, DP_POLL, 0xFFFFF5FFC93FF880)           = 1
/1:     open("/dev/xde", O_RDWR|O_CLOEXEC)              = 11
/1:     ioctl(11, _IOWRN('w', 1, 119), 0xFFFFF5FFFFDDBB68) Err#71 EPROTO
```

Looking at my omicron repo that I packaged from:
```
$ cat tools/opte_version
0.25.183
```

vs what `opteadm` reports:
```
# /opt/oxide/opte/bin/opteadm -V
opteadm 0.23.181
```

It seems like this info should be included with the Rust type provided by thiserror but we don't see any information about the failed ioctl call in sled-agent's logs.
```
    #[error("Failed to delete all XDE devices")]
    DeleteXdeDevices(#[source] illumos_utils::opte::Error),
```

**Comment by luqmana** [comment]
Ok yea, we definitely have the mismatched error but I misremembered where, it's in opte and not omicron.

We'd either see the [`IoctlFailed`](https://github.com/oxidecomputer/opte/blob/faaf3320e673167722c2c7e6fb2a86bd84f04a8a/lib/opte-ioctl/src/lib.rs#L40-L42) variant
```rust
    /// Something in the opte ioctl(2) handler failed.
    #[error("ioctl {0:?} failed: {1}")]
    IoctlFailed(OpteCmd, String),
```
where the `String` would be `"API version mismatch"` (set [here](https://github.com/oxidecomputer/opte/blob/faaf3320e673167722c2c7e6fb2a86bd84f04a8a/lib/opte-ioctl/src/lib.rs#L251) for commands without a response).

Or, for some commands, a specific [`CommandError`](https://github.com/oxidecomputer/opte/blob/faaf3320e673167722c2c7e6fb2a86bd84f04a8a/lib/opte-ioctl/src/lib.rs#L59-L60) (constructed [here](https://github.com/oxidecomputer/opte/blob/faaf3320e673167722c2c7e6fb2a86bd84f04a8a/lib/opte-ioctl/src/lib.rs#L243-L248) for commands with a response):
```rust
    #[error("command {0:?} failed: {1:?}")]
    CommandError(OpteCmd, OpteError),
```
Where that `OpteError` field would be [`BadApiVersion`](https://github.com/oxidecomputer/opte/blob/faaf3320e673167722c2c7e6fb2a86bd84f04a8a/crates/opte-api/src/cmd.rs#L138-L141):
```rust
    BadApiVersion {
        user: u64,
        kernel: u64,
    },
```

The issue here I think is that the "higher level" omicron error `DeleteXdeDevices` just needs to reference the opte error it wraps:

```rust
    #[error("Failed to delete all XDE devices: {0}")]
    DeleteXdeDevices(#[source] illumos_utils::opte::Error),
```

[`BootstrapError`](https://github.com/oxidecomputer/omicron/blob/63ca0f9d9603ee486241be1d541cdcc5101e9dc2/sled-agent/src/bootstrap/mod.rs#L47-L48) seems like it could do with the same treatment as well:
```rust
    #[error("Error managing guest networking")]
    Opte(#[from] illumos_utils::opte::Error),
```

**Comment by jgallagher** [comment]
> The issue here I think is that the "higher level" omicron error DeleteXdeDevices just needs to reference the opte error it wraps:
>
> ```rust
>   #[error("Failed to delete all XDE devices: {0}")]
>    DeleteXdeDevices(#[source] illumos_utils::opte::Error),
> ```
>
> [BootstrapError](https://github.com/oxidecomputer/omicron/blob/63ca0f9d9603ee486241be1d541cdcc5101e9dc2/sled-agent/src/bootstrap/mod.rs#L47-L48) seems like it could do with the same treatment as well:
>
> ```rust
>    #[error("Error managing guest networking")]
>    Opte(#[from] illumos_utils::opte::Error),
> ```

I think embedding the error via `{0}` is what dtolnay has said never to do with thiserror, at least a few years ago. From https://users.rust-lang.org/t/do-people-not-care-about-printable-error-chains-a-k-a-how-to-nicely-implement-display-for-an-error/35362/2:

> Using [thiserror](https://github.com/dtolnay/thiserror)'s attribute syntax for convenience, the contents of the error type should appear either in the message:
>
> ```rust
> #[derive(Error)]
> enum Error {
>    #[error("Failed to read settings: {0}")]
>    ReadSettings(io::Error),
> }
> ```
> or as a source:
>
> ```rust
> #[derive(Error)]
> pub enum Error {
>     #[error("Failed to read settings")]
>     ReadSettings(#[source] io::Error),
> }
> ```
> but never both.

I think instead of adjusting the error cases, we should be fixing wherever errors are printed or logged to use something like [DisplayErrorChain](https://docs.rs/display-error-chain/latest/display_error_chain/struct.DisplayErrorChain.html) to show the full chain of errors.

**Comment by papertigers** [comment]
I need to go look how we print these errors, but as a quick experiment:

```rust
use thiserror::Error;

#[derive(Debug, Error)]
enum MyError {
    #[error("Got an error")]
    Foo(#[source] std::io::Error),
}

#[derive(Debug, Error)]
enum OtherError {
    #[error("Nested errors")]
    Bar(#[source] MyError),
}

fn main() -> Result<(), OtherError> {
    Err(std::io::Error::new(std::io::ErrorKind::Other, "oh no!"))
        .map_err(MyError::Foo)
        .map_err(OtherError::Bar)?;
    Ok(())
}
```

```
❯ cargo r
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/scratch`
Error: Bar(Foo(Custom { kind: Other, error: "oh no!" }))
```

And when using anyhow

```rust
use thiserror::Error;

#[derive(Debug, Error)]
enum MyError {
    #[error("Got an error")]
    Foo(#[source] std::io::Error),
}

#[derive(Debug, Error)]
enum OtherError {
    #[error("Nested errors")]
    Bar(#[source] MyError),
}

fn main() -> anyhow::Result<()> {
    Err(std::io::Error::new(std::io::ErrorKind::Other, "oh no!"))
        .map_err(MyError::Foo)
        .map_err(OtherError::Bar)?;
    Ok(())
}
```

```
❯ cargo r
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/scratch`
Error: Nested errors

Caused by:
    0: Got an error
    1: oh no!
```

**Comment by jgallagher** [comment]
Yeah, anyhow has a lot more fancy options for printing. https://docs.rs/anyhow/latest/anyhow/struct.Error.html#display-representations covers what you're seeing with that example:

> The Debug format “{:?}” includes your backtrace if one was captured. Note that this is the representation you get by default if you return an error from fn main instead of printing it explicitly yourself.

For experiments I think I'd try explicitly printing instead of returning from main, although even with that anyhow gives a lot more options. Its `{:#}` format is pretty analogous to wrapping a `thiserror` error in `DisplayErrorChain`, I think.

**Comment by papertigers** [comment]
I am wondering if we could instead use `#[error(transparent)] from thiserror

> Errors may use error(transparent) to forward the source and Display methods straight through to an underlying error without adding an additional message. This would be appropriate for enums that need an “anything else” variant.

That or do something like make `CmdError` use `Box<dyn std::error::Error>`
