### ISSUE TITLE
ClickHouse tests do not always clean up after themselves

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/omicron#4634]
[This config file](https://github.com/oxidecomputer/omicron/blob/9859e12b86b4f73fd4e0592787f480972d83c8d1/nexus/preprocessed_configs/config.xml) seems to be leftover from an unclean exit of a ClickHouse test. We should investigate why it is not removed with other files. I don't have any concrete evidence that the replicated tests create this file, but I don't recall seeing them prior to those merging in.

**Comment by karencfv** [comment]
Ah, that's a bummer :( 

It's unlikely that it's the replicated tests since the preprocessed file would have additional configuration settings from the `replica_config.xml` or `keeper_config.xml` files.

Also, I think these lines give a clue that it's probably from a single node test. It says this file is generated when the server is run without a config file, and the replicated tests are run with the config files I mentioned above.

https://github.com/oxidecomputer/omicron/blob/9859e12b86b4f73fd4e0592787f480972d83c8d1/nexus/preprocessed_configs/config.xml#L3-L6

**Comment by sunshowers** [comment]
Definitely related to #4080.
