### ISSUE TITLE
Add sled process needs to do more of what RSS does

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#4651]
Currently the add sled process successfully inducted a new sled into the cluster (learning network config and rack secrets). But the sled has not gone through RSS for service zone assignment so it has only a global zone. For this reason, the sled is not usable for propolis and storage.

**Comment by askfongjojo** [comment]
From initial discussions with @davepacheco and @smklein:
- zpools should be created and in the database already
- need to provision new crucible and NTP zones on the new sled
- db "services" table needs to be updated for the new zones
- various db dns tables need to be updated (there's not a good way to do this behind Nexus's back)
- something special with datasets?
- possibly something related to #4652 

And there may be more after more digging into what RSS passes to Nexus.

Pointers: The datasets RSS currently passes to Nexus during the handoff are [converted into DB models](https://github.com/oxidecomputer/omicron/blob/8fa550c2c95b5fd3443af7e2e5837c2178fdb8c8/nexus/src/app/rack.rs#L104-L115), [passed to db::rack_set_initialized](https://github.com/oxidecomputer/omicron/blob/8fa550c2c95b5fd3443af7e2e5837c2178fdb8c8/nexus/src/app/rack.rs#L227), and [inserted into the database](https://github.com/oxidecomputer/omicron/blob/8fa550c2c95b5fd3443af7e2e5837c2178fdb8c8/nexus/db-queries/src/db/datastore/rack.rs#L646-L673)

**Comment by davepacheco** [comment]
I'm not sure what a better synopsis for this issue should be but I feel like the synopsis right now implies this is a much smaller project than it is.  Maybe "add sled process needs to do more of what RSS does"?

**Comment by askfongjojo** [comment]
> I'm not sure what a better synopsis for this issue should be but I feel like the synopsis right now implies this is a much smaller project than it is. Maybe "add sled process needs to do more of what RSS does"?

True. I updated the issue subject line to better reflect the scope of work. The other thing we talked about was that ideally the service rebalancing process to be built for software update should take care of provisioning service zones on a new sled (as opposed to having a third way of achieving the same thing in the add-sled workflow).

Lastly, I just noticed that Nexus started placing workload onto the new sled after the recent software update. It seems that Nexus maintains a cache of the sleds (even though it queries their available capacity live from the sled db table). If so, another necessary change is for the add sled process to invalidate the Nexus sled cache.

**Comment by andrewjstone** [comment]
I did a detailed reading of the RSS code and here is what I found:

# What does RSS actually do when triggered?

See the [doc comment](https://github.com/oxidecomputer/omicron/blob/7c3cd6abe9d957a51465209497064fb133854932/sled-agent/src/rack_setup/service.rs#L5-65) for a high-level overview.

All of the below running of RSS starts inside the task running [`ServiceInner::run`](https://github.com/oxidecomputer/omicron/blob/7c3cd6abe9d957a51465209497064fb133854932/sled-agent/src/rack_setup/service.rs#L774-L1092).

We are going to go through this function and identify the important actions that happen when RSS is run and identify all of them that do not happen when an uninitialized sled is added via the sled-agent API after rack initialization has run. We will ignore the code paths that check to see if the plan has already run partially or to completion, as these are not directly relevant to our task.

For each action below, we will denote whether it already exists as part of adding a sled with the `(Done)` prefix in the action heading. If the action is not yet performed we will write `(Needs Work)`. If the action is irrelevant when adding a sled we will mark it `(N/A)`.

### (N/A) Create a sled plan for all initial sleds

First we configure a sled plan for all initial sleds: [This structure](https://github.com/oxidecomputer/omicron/blob/7c3cd6abe9d957a51465209497064fb133854932/sled-agent/src/rack_setup/plan/sled.rs#L46-L53) ends up getting serialized and persisted in a file on each M.2 on the RSS node. The plan contains the [initial configuration request](https://github.com/oxidecomputer/omicron/blob/7c3cd6abe9d957a51465209497064fb133854932/sled-agent/src/bootstrap/params.rs#L47-L93) sent from wicketd.

This plan contains the [`StartSledAgentRequest`](https://github.com/oxidecomputer/omicron/blob/7c3cd6abe9d957a51465209497064fb133854932/sled-agent/src/bootstrap/params.rs#L216-L232) that will be sent to every bootstrap agent o initialize itself. Importantly, the underlay subnet for the sled and it's UUID are allocated here.

### (Done) - Initialize the trust quorum

This creates an initial membership set and kicks off a rack initialization via the local bootstore node.

This work is already covered when adding a sled. The newly added sled becomes a `learner` node and is capable of receiving a key share from existing trust quorum members.

### (Done) - Save the EarlyNetworkConfig in the bootstore

This configuration contains the set of ntp servers as well as the [`RackNetworkConfig`](https://github.com/oxidecomputer/omicron/blob/7c3cd6abe9d957a51465209497064fb133854932/common/src/api/internal/shared.rs#L71-L88) required to provide enough networking configuration to configure uplinks and reach external NTP servers required for CockroachDB to boot.

This work is already covered when adding a sled. The newly added sled learns its bootstore config from other sleds on the bootstrap network that already have it.

### (Done) Send the `StartSledAgentRequest` to each sled over a sprockets (currently tcp) channel

This eventually results in a call to [`start_sled_agent`](https://github.com/oxidecomputer/omicron/blob/7c3cd6abe9d957a51465209497064fb133854932/sled-agent/src/bootstrap/server.rs#L353-L435)  which unlocks storage via trust quorum, advertises the underlay network prefix of the sled-agent via DDMD, and starts the Sled Agent HTTP server. This request is also persisted so that cold boot works.

Importantly, this exact same function is called currently when adding a sled, and so all functionality works correctly.

### (Done) Disks and zpools get added to Nexus

As a result of unlocking storage via the trust quorum, disks get configured and [[Nexus is notified](https://github.com/oxidecomputer/omicron/blob/7c3cd6abe9d957a51465209497064fb133854932/sled-agent/src/storage_monitor.rs#L133-L177) about them via the `StorageMonitor` task, which itself learns about existing disks from the `StorageManager` task which is responsible for ensuring disks detected from `HardwareManager` are configured (including establishment of an encrypted root dataset with keys derived from the trust quorum rack secret for U.2 devices) and ready to use.

### (Done) The sled gets added to the `sled` table
As part of starting sled-agent, the sled-agent will inform nexus about itself resulting in its population in the CRDB `sled` table.

### (Needs Work) Establish a service Plan

Right now, services are not reconfigured at run time by the control plane. An initial plan for where services will run based on the initial set of servers is [created by RSS](https://github.com/oxidecomputer/omicron/blob/main/sled-agent/src/rack_setup/plan/service.rs#L705-L752) and then executed to deploy the zones running those service instances. We require the ability for Nexus to modify this plan as new servers are added to a rack (and eventually multiple racks) such that services can be allocated correctly to the new sleds. Importantly, we need to be able to migrate services off existing sleds and onto new sleds such that they maintain the required redundancy. For example, if we want to remove a sled running Nexus or a boundary NTP server, we need to be able to ensure that we are running another instance of Nexus and another boundary NTP server before removing that sled. In some cases, the sled has already been physically removed, but the information in CRDB does not reflect this reality. The update of CRDB is part of "service planning", while the deployment of zones is part of service plan execution.

The service plan itself allocates a zone for each service instance with an underlay address and internal DNS records. Some zones also require persistent datasets to be allocated for them. The planner choses which available U.2 drive to allocate the `zoned` datasets to. While the switch zone is special, as the sled-agent automatically starts the switch zone, there is still configfuration required of it during RSS setup. We include it below, because scrimlets may also be added or removed and we need to account for the distinct services running on these scrimlets as well.

| Service | Zone | Zone Dataset on U.2 | Extras needed |
| ------- | ---- | ------------------- | ------------ |
| Dendrite| Switch  | No | - |
| MGS     | Switch  | No | - |
| Internal DNS | Service | Yes | - |
| CRDB | Service |  Yes |
| External DNS | Service | Yes | - |
| Nexus | Service | No | Nic, External Ip, External DNS, External TLS |
| Oximeter | Service | No | - |
| Clickhouse | Service | Yes | - |
| Clickhouse Keeper | Service | Yes | - |
| Crucible Pantry | Service | No | - |
| Crucible | Service | No | - |
| Boundary NTP | Service |  No | Nic, External NTP + DNS, SNAT config |

### (Needs Work) Executing the service plan

After a plan is established and persisted to the M.2s on the RSS node, it must be executed. This means configuring DNS, creating datasets allocated to U.2s, and deploying zones allocated to sleds.

Importantly, for RSS [zones are started in a specific order](https://github.com/oxidecomputer/omicron/blob/main/sled-agent/src/rack_setup/service.rs#L976-L998). Internal DNS and NTP are started first, then we wait for timesync, then start CRDB, and the rest of the services. Once all services are initialized, we mark the execution of the initial RSS service plan complete in a ledger on the M.2s on the RSS sled. Lastly, we [`handoff_to_nexus`](https://github.com/oxidecomputer/omicron/blob/main/sled-agent/src/rack_setup/service.rs#L541-L691) which ensures that the provisioned services and datasets, the `RackInitializationRequest` used to initialize the rack, and the actual rack network config, are persisted in CRDB, so that Nexus can now take over for future provisioning tasks. At this point RSS is complete.

All zones are initialized via a call to [`initialize_zone_on_sled`](https://github.com/oxidecomputer/omicron/blob/main/sled-agent/src/rack_setup/service.rs#L270-L352)

Swtich Management addresses are learned from the EarlyNetworkSetup stored in the bootstore.


### (Needs work) Handoff to Nexus

When services are provisioned to Nexus, a request is made to inform nexus about each service and its corresponding dataset if one exists. When we execute the plan from Nexus for adding/removing sleds we'll need to send these or similar requests to modify the relevant CRDB tables.

**Comment by davepacheco** [comment]
I think we've effectively finished this off at this point.  With bits from "main", we've successfully added a new sled and used it for both customer instances and storage.
