### ISSUE TITLE
More detail in default ip-pool lookup failures

### ISSUE THREAD

**Issue by internet-diglett** [oxidecomputer/omicron#4864]
Recently when troubleshooting the cause of an instance failing to deploy, I saw that I was hitting an error that showed the `ip-pool` could not be found. I was looking the the logs to see which `ip-pool`, I only saw "Default pool for current silo" in the log message. Should we also provide the UUID or name being used in the query, so we actually know _what_ failed to be found?

https://github.com/oxidecomputer/omicron/blob/c794b1a33f6fbb500723b8c3ced9595b390f66a7/nexus/db-queries/src/db/datastore/ip_pool.rs#L187-L193

**Comment by david-crespo** [comment]
Thanks for flagging this as a source of confusion.

The reason I am returning that unhelpful string is that we're looking up the pool by (roughly) `silo_id = <current_silo_id> and is_default = true`. So there is no pool name or ID involved for me to put in the message. When this query fails to find something, the problem is that no pool has been set up as the default for the silo. Hence the message, but I see now that it sounds like it's complaining about a particular pool, namely the default for the silo, rather than the fact that there is no such pool. Will fix!

**Comment by internet-diglett** [comment]
Thanks @david-crespo, that clarifies things a lot! I was kinda scratching my head because I interpreted it _exactly_ as you said 😂
