### ISSUE TITLE
Better error on instance create if there is no default IP pool

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#4954]
Replication steps (all performed via Console):
1. Fleet admin linked an ip pool to a silo
2. Fleet admin set the ip pool as silo default pool.
3. Fleet admin unlinked the default ip pool from silo.
4. Silo user attempts to create a new instance and hit "Object not found" error.

This is the error recorded in the `saga_node_event` table:
```
 {"ActionFailed": {"source_error": {"ObjectNotFound": {"lookup_type": {"ByOther": "default IP pool for current silo"}, "type_name": "ip-pool"}}}} 
```

**Comment by askfongjojo** [comment]
Even though it is a user error, the failure mode is obscure and we probably want to prevent the operator from unlinking a default ip-pool.

**Comment by david-crespo** [comment]
That would mean requiring every silo to have a default pool, which would mean we would have to create and assign one (or choose an existing pool) at silo create time. For existing systems, we would have to decide on a way to assign default pools to existing silos that don't have one. Sounds reasonable?

The failure mode is definitely weird. We ran into that in https://github.com/oxidecomputer/omicron/issues/4864 — the error message used to be even worse.

The alternative to the above would be to add more info to the API error (and the console's handling of it) to make it clearer what the problem is when there is no default.

**Comment by askfongjojo** [comment]
A better error message will do (Something to the effect of “No default IP pool is found for this silo. Contact your administrator…”). This way we don’t have to put guard rails everywhere.

**Comment by david-crespo** [comment]
I got myself worked up thinking about fixing the message, changing the status from 404 to 503 or 507, etc. But I've realized the bigger issue here is that in the console we are not displaying the message from the API! We just say "Object not found", which is totally useless. So I will start by fixing that.

![image](https://github.com/oxidecomputer/omicron/assets/3612203/475fe931-2f6e-4fdf-b1c5-df0ff1da2fea)

**Comment by david-crespo** [comment]
Giving a shot to fixing this on the console side only. "Contact administrator" is slightly awkward to put in the API error message, so I'd like to leave it out for now.


https://github.com/oxidecomputer/console/pull/1935

![image](https://github.com/oxidecomputer/omicron/assets/3612203/3bd02374-3189-486d-9183-370a8572435c)
