### ISSUE TITLE
Sled agent fails to get past ensuring ledgered zones when a dataset goes missing

### ISSUE THREAD

**Issue by augustuswm** [oxidecomputer/omicron#5002]
#4853 added checks for properties on datasets during sled-agent startup (`ensure_all_omicron_zones`). This requires that datasets that have been recorded to the `services.json` ledger are available on the next startup. If any dataset is not ready, `ensure_all_omicron_zones` will bail out and restart after a timeout. If a dataset has gone missing (i.e. disk removal) then this function can never complete and will loop forever, stopping the remaining zones from starting, and any other work sled-agent needs to do after the zones start.

While we don't support drive removal currently we likely want to allow getting past this invalid state in the meantime.

Log message that is repeated:
```
17:29:21.438Z WARN SledAgent: Failed to load services, will retry in 223.810606507s
    error = GetZfsValue { zone: "oxz_crucible_41f07d39-fcc0-4796-8b7c-7cfcd9135f78", source: GetValueError { filesystem: "oxp_4b90abdc-3348-4158-bedc-5bcd56e281d8/crucible", name: "[\\"zoned\\", \\"canmount\\", \\"encryption\\"]", err: Execution(CommandFailure(CommandFailureInfo { command: "/usr/sbin/zfs get -Ho value zoned,canmount,encryption oxp_4b90abdc-3348-4158-bedc-5bcd56e281d8/crucible", status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "cannot open 'oxp_4b90abdc-3348-4158-bedc-5bcd56e281d8/crucible': dataset does not exist\\n" })) } }
    file = sled-agent/src/sled_agent.rs:612
    sled_id = da89d292-1e33-4c21-8cc2-65b6ef9cbb1b

```

**Comment by smklein** [comment]
See also: https://github.com/oxidecomputer/omicron/issues/2973

In `ensure_all_omicron_zones`, the check we added [validates that the dataset being used by the zone exists before using it](https://github.com/oxidecomputer/omicron/blob/7e0ce9905ecf46e815f370b4cb5b1dfc05a36096/sled-agent/src/services.rs#L2985-L3048), but this is basically intended to give a better error message. We expect that starting the zone would also fail if it's configured to use a missing dataset. I guess we must have been "starting" the zone, but not seeing the failure to boot.

I agree that "unplugging a disk on a sled that's powered off" needs to be a case we support. There's more work upstack to make sure nexus fully reconciles the view of the world, but in the meantime, I'll do the following:

`ensure_all_omicron_zones`: This clearly need to attempt to launch all zones, but I still want it to return an error in this case, if we detect that something has gone wrong.

`load_services` is a bit more complicated. It attempts to launch internal DNS first, then NTP, then all other zones. Internal DNS sits on a dataset, so it's possible that a disk which was unplugged was backing the internal DNS system, in which case the sled would be unable to make progress. In your logs, we **happened** to be trying to start a Crucible zone, but any zone with durable storage could be hit here.

https://github.com/oxidecomputer/omicron/blob/7e0ce9905ecf46e815f370b4cb5b1dfc05a36096/sled-agent/src/services.rs#L872-L977

Explicitly tries to boot "internal DNS first, then NTP, then all other zones", because "NTP depends on Internal DNS", and "other things depend on NTP".

In the limit, it seems like we should be *able* to boot "as many zones as we can" concurrently, and keep retrying until we converge on a set that works or Nexus tells us to try something different. But this seems like it'll be dependent on all zones sufficiently retrying, when their dependencies might not exist yet.

**Comment by smklein** [comment]
I created two possible mitigations for this issue. One is low-risk but IMO worse, the other is higher-risk but IMO preferable.

## Option 1: [Ignore zones with invalid storage](https://github.com/oxidecomputer/omicron/pull/5008)

(This change is smaller than it looks, it's mostly refactoring)

This change basically takes a call to `validate_storage_and_pick_mountpoint` -- which selects a viable U.2 to use, that might be one the zone needs as a durable dataset anyway -- and if it cannot be selected, the zone is ignored.

- Pro: It's simple
- Pro: It should fix this issue, technically
- Con: It's weird that the zone is silently dropped, this feels like a footgun
- Con: If the disk isn't "ready yet" -- perhaps it hasn't finished enumerating? -- it feels possible for us to miss it.

## Option 2: [Make zones launch more independently of each other](https://github.com/oxidecomputer/omicron/pull/5012)

This change removes the dependency between NTP, internal DNS, etc, and makes zone initialization more independent for each individual zone within a request.

- Pro: IMO this makes the overall API to launch sleds simpler
- Pro: IMO removing this hard-coded ordering is a better, more fault-tolerant change for us to undertake
- Con: This change is larger, and removing this serialization means that zones must be able to cope with a more arbitrary boot order

**Comment by smklein** [comment]
My preference is to move forward on option (2), if we can validate it sufficiently.

**Comment by augustuswm** [comment]
Option 2 definitely sounds like the better one in practice. Having zones fail silently definitely sounds dangerous. My thoughts are around which of these we can get in to release 6, and does using option 1 preclude us from switching to option 2 for release 7.

It sounds like option 1 is roughly reverting to the behavior of the release 5 system, while incorporating the property checks when a dataset is available. This should be pretty safe to include in release 6. Once we cut off release 6, we could switch to option 2 and then have a full cycle to validate it.
