### ISSUE TITLE
Newly added sleds are not on rack subnet

### ISSUE THREAD

**Issue by andrewjstone** [oxidecomputer/omicron#5009]
I added a sled `g2` to an existing rack. The subnet should be `fd00:1122:3344:100/56`, but I ended up with a sled ip of `fd00:1122:3344:21::1`

**Comment by andrewjstone** [comment]
It actually looks like the prefix in the `rack` table is wrong. 

```
root@[fd00:1122:3344:102::3]:32221/omicron> select * from rack;
                   id                  |         time_created         |         time_modified         | initialized | tuf_base_url |      rack_subnet
---------------------------------------+------------------------------+-------------------------------+-------------+--------------+------------------------
  0b040fee-f596-4c1a-9751-4e8cc4961cdd | 2024-02-06 18:23:30.58455+00 | 2024-02-06 18:24:12.767641+00 |    true     | NULL         | fd00:1122:3344:1::/56
(1 row)


Time: 90ms total (execution 87ms / network 3ms)
```

**Comment by andrewjstone** [comment]
Alright, it appears we introduced a bug in between when dogfood was setup and now. The rack prefix is correct on dogfood, but wrong on madrid where we constantly run RSS. On madrid it is the same as my testbed.

**Comment by jgallagher** [comment]
It looks like there are a few going on here, and they're kind of spread out.

The `RackInitializeRequest` that is sent from wicket to sled-agent to kick off RSS has a [`rack_subnet`](https://github.com/oxidecomputer/omicron/blob/8f1e4191fb75592d130fb4b5ed7f9fbdba1dbd20/sled-agent/src/bootstrap/params.rs#L56) field. This is the field RSS uses when it assigns [sled_subnets](https://github.com/oxidecomputer/omicron/blob/8f1e4191fb75592d130fb4b5ed7f9fbdba1dbd20/sled-agent/src/rack_setup/plan/sled.rs#L100) ([`sled_subnet()`](https://github.com/oxidecomputer/omicron/blob/8f1e4191fb75592d130fb4b5ed7f9fbdba1dbd20/sled-agent/src/rack_setup/config.rs#L76-L84)).

`RackInitializeRequest` also contains a [`rack_network_config`](https://github.com/oxidecomputer/omicron/blob/8f1e4191fb75592d130fb4b5ed7f9fbdba1dbd20/sled-agent/src/bootstrap/params.rs#L91-L92) field. `RackNetworkConfig`, in addition to details about uplinks and BGP, has _another_ [`rack_subnet`](https://github.com/oxidecomputer/omicron/blob/8f1e4191fb75592d130fb4b5ed7f9fbdba1dbd20/common/src/api/internal/shared.rs#L78) field, that is unrelated to the above `rack_setup`, at least at the type system. (You probably already imagine where this is going if these are different!)

When sled-agent does the handoff to Nexus, builds a Nexus [`RackInitializeRequest`](https://github.com/oxidecomputer/omicron/blob/8f1e4191fb75592d130fb4b5ed7f9fbdba1dbd20/sled-agent/src/rack_setup/service.rs#L660-L670), which is not the same as the wicket to sled-agent `RackInitializeRequest` linked above. In particular, this one does not have the top-level `rack_subnet` field, but does still have the `rack_network_config` field, which sled-agent dutifully copies. Nexus eventually [stores the `rack_network_config.rack_subnet` value](https://github.com/oxidecomputer/omicron/blob/8f1e4191fb75592d130fb4b5ed7f9fbdba1dbd20/nexus/src/app/rack.rs#L226) in CRDB.

In wicket, we currently hard-code the [`RACK_SUBNET`](https://github.com/oxidecomputer/omicron/blob/8f1e4191fb75592d130fb4b5ed7f9fbdba1dbd20/wicketd/src/rss_config.rs#L38-L42) value we pass as the top-level rack subnet that RSS uses to allocate sled IPs. This prefix matches the IPs everyone knows and loves from dogfood, madrid, and the testbed. However, we accept the `rack_network_config` from the user, and our latest/current `madrid.toml` RSS input has this bit:

```toml
[rack_network_config]
rack_subnet = "fd00:1122:3344:01::/56"
```

That `:01` should be `:0100` to match the hardcoded `RACK_SUBET`, but we don't have anything that checks that. We pass this incorrect rack_subnet along and it eventually lands in CRDB, even though it's not the one we used when setting up the rack.

It looks like most of this was probably introduced in #3986. Before that PR, we didn't store the rack subnet in CRDB at all! I think that means that only racks that have gone through RSS since that PR landed _may_ have this issue, and whether they actually do will depend on the `rack_network_config` they were given at RSS time. I haven't yet tracked down how a rack that was set up before that PR gets a non-NULL `rack_subnet` value in CRDB, but presumably that code is correct, since dogfood has the correct rack_subnet value in CRDB.
