### ISSUE TITLE
IP ranges in pools should only be IPv4

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#5085]
The IP range add/remove endpoints allow pairs of v4 or v6 addresses, and have done so since they were added in https://github.com/oxidecomputer/omicron/pull/1253 (June 2022).

https://github.com/oxidecomputer/omicron/blob/235420ebd04831829ff3b2ce89fcd26f38c768f5/common/src/address.rs#L351-L361

I only just found out that while the API lets you add and remove them, IPv6 address ranges will not actually work from a networking POV — it's possible we can allocate an IPv6 address to an instance, but the instance will not be reachable through it.

The simplest thing would be to change the endpoint to take an `Ipv4Range` instead of an `IpRange`. That is probably not as a simple as it sounds — there will be a lot of fiddly changes to the tests.

https://github.com/oxidecomputer/omicron/blob/235420ebd04831829ff3b2ce89fcd26f38c768f5/nexus/src/external_api/http_entrypoints.rs#L1731-L1741

**Comment by bnaecker** [comment]
Could you explain more about why we'd remove this? It's true that support for IPv6 has been deferred, but it's not abandoned AFAIK. One cannot add an IPv6 address to an instance at this point, since there are a number of places that check that condition and return a 400. A client gets a pretty immediate notification that this failed, rather than just an unreachable instance.

**Comment by bnaecker** [comment]
> What I want to avoid is mysterious failures in this scenario:

I agree.

> What I need to find out in detail is: what happens at this point? Where does the 400 actually happen?

It does not today, which is news to me. When we added all these APIs, there were several places that checked for requests for external IPv6 and returned a 400. I can't find those anymore. I'm not sure what actually happens, but I'm looking at it now.

**Comment by bnaecker** [comment]
Ok, so this is definitely not great right now. You certainly can create a pool with IPv6 ranges, and instance with an IPv6  address from that pool.

```
bnaecker@shale : ~/omicron $ oxide ip-pool range list --pool 2ab2c2f6-dd89-4107-a478-3ebd80827262
IpPoolRange {
    id: b34db578-c7de-4da1-9789-0ea81196cd0c,
    ip_pool_id: 2ab2c2f6-dd89-4107-a478-3ebd80827262,
    range: V6(
        Ipv6Range {
            first: fd00::1,
            last: fd00::10,
        },
    ),
    time_created: 2024-02-16T21:16:01.893937Z,
}
bnaecker@shale : ~/omicron $ oxide instance list --project test
Instance {
    description: "my inst",
    hostname: "test",
    id: 8344c09c-1ca6-43d5-aa85-6962c7ba40d0,
    memory: ByteCount(
        1073741824,
    ),
    name: Name(
        "test",
    ),
    ncpus: InstanceCpuCount(
        2,
    ),
    project_id: e49c211b-603e-49ba-95d4-455176f965fc,
    run_state: Stopped,
    time_created: 2024-02-16T21:17:18.784391Z,
    time_modified: 2024-02-16T21:17:18.784391Z,
    time_run_state_updated: 2024-02-16T21:18:40.983355Z,
}
bnaecker@shale : ~/omicron $ oxide instance external-ip list --instance 8344c09c-1ca6-43d5-aa85-6962c7ba40d0
success
ExternalIpResultsPage {
    items: [
        ExternalIp {
            ip: fd00::2,
            kind: Ephemeral,
        },
    ],
    next_page: None,
}
```

But you get a 500 when _starting_ the instance:

```
bnaecker@shale : ~/omicron $ oxide instance start --instance 8344c09c-1ca6-43d5-aa85-6962c7ba40d0
error
Error Response: status: 500 Internal Server Error; headers: {"content-type": "application/json", "x-request-id": "56c0099b-2d58-45c6-a88c-cbccde1c07f1", "content-length": "124", "date": "Fri, 16 Feb 2024 21:18:41 GMT"}; value: Error { error_code: Some("Internal"), message: "Internal Server Error", request_id: "56c0099b-2d58-45c6-a88c-cbccde1c07f1" }
```

That comes from here:

```
{"msg":"request completed","v":0,"name":"nexus","level":30,"time":"2024-02-16T21:18:41.144205856Z","hostname":"oxz_nexus_9daee106-8cf8-4873-96ae-c6e0925b38d8","pid":2054,"uri":"//v1/instances/8344c09c-1ca6-43d5-aa85-6962c7ba40d0/start","method":"POST","req_id":"56c0099b-2d58-45c6-a88c-cbccde1c07f1","remote_addr":"192.168.1.82:39978","local_addr":"172.30.2.5:80","component":"dropshot_external","name":"9daee106-8cf8-4873-96ae-c6e0925b38d8","file":"/home/bnaecker/.cargo/git/checkouts/dropshot-a4a923d29dccc492/711a749/dropshot/src/server.rs:837","error_message_external":"Internal Server Error","error_message_internal":"saga ACTION error at node \"dpd_ensure\": ipv6 nat is not yet implemented","latency_us":330254,"response_code":"500"}
```

So the _current_ blocker is that IPv6 NAT isn't implemented, here:

https://github.com/oxidecomputer/omicron/blob/9e9e60c7f6456c721348e9edb1b432d310e4b7aa/nexus/src/app/instance_network.rs#L480-L485

Given how much this has obviously changed since I've last looked at the code, I have no idea how many other blockers exist even if we clear this one.

I generally agree with your point @david-crespo, that the current behavior is confusing and a bad experience. I also don't particularly want to unwind support or modify tests, since we do still want to support IPv6. (I don't know how far away we are from that though.)

Rather than changing the API, tests, etc., could we instead quickly fail a request if IPv6 is used? I think doing so at the range-add API would make sense, but I'm not positive about that.

**Comment by david-crespo** [comment]
Yes, I think 400ing on IPv6 address ranges would not be very invasive and it avoids the whole problem while we figure things out.
