### ISSUE TITLE
OxQL: want single most recent data point from a time range

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#5436]
An OxQL op that will lower to `ORDER BY timestamp DESC LIMIT 1`.

**Comment by bnaecker** [comment]
A table op like: `...<rest of query>... | last 4` would be nice.

**Comment by david-crespo** [comment]
That would be great. If there are multiple timeseries, would it apply to each one separately? I haven't spent enough time with OxQL yet to develop intuitions about this.

**Comment by bnaecker** [comment]
Good question, I also don't know. My gut is "yes", that's separate for each timeseries, so that operations like a `join` would still work after this one.

**Comment by bnaecker** [comment]
Ok, so this one is interesting. I actually started to implement this in the original PR for OxQL, but it's pretty gnarly. We try really hard to do as much filtering _in the database_ as possible, in order to limit the data being transferred to us in the first place. This is especially important for the measurement tables, which are **much** larger than the field tables. So we do things like push the timestamp filters down to the database, for example.

However, we also try to limit the number of queries we need to run. Each one has a bunch of setup for us; a bunch of parsing / deserialization in the database; reading all the data; etc etc. It's nice if we can pack that together into a small number of queries.

For _this_ table operation to work in the database, we would need to either:

- run one query per timeseries (individual timeseries key), so that each gets a bog-standard SQL `ORDER BY timestamp DESC LIMIT k` clause appended to it.
- do some extremely complex query, possibly with some [array join](https://clickhouse.com/docs/en/sql-reference/functions/array-join) magic, in order to apply a limit to each timeseries independently. For example, you could imagine running the query we already do, but doing grouping like `SELECT timeseries_key, groupArray(datum) FROM measurements_table WHERE timeseries_key IN (1, 2, 3, ...) AND timestamp > t0 GROUP BY timeseries_key`; and then applying an array function like `arraySlice(arr, -k)` to get the last `k`; and then "unrolling" that array again using `arrayJoin()`. I've tried to write things like this many times before, but one of the main reasons for OxQL in the first place was to _avoid_ that!

Luckily, there's a third option, I think: we don't do it in the DB, but in Rust. Applying a `last k` table operation in OxQL is very easy. The downside is that we may end up transferring much more data than otherwise. For example, if you make a huge range here, like `get foo | filter timestamp > @now() - 1y | last 1`, then we'll select the last year of data and probably throw almost all of it away _after_ deserializing it from the database. But that's an optimization we can fix, if this query becomes a big hot-spot.

**Comment by bnaecker** [comment]
There may be another approach using window functions, but I think that will also be very complicated to write correctly.

**Comment by david-crespo** [comment]
Selecting a million points to get 1 sounds pretty bad to me. Worth testing how the multiple query option performs before ruling it out.

**Comment by bnaecker** [comment]
The array-join approach is maybe not as bad as I remember. This correctly fetches the last 5 timestamps from two different timeseries:

```
shale :) with foo as (select timeseries_key, arraySlice(arraySort(groupArray(timestamp)), -5) as timestamp from measurements_cumulativeu64 where timeseries_name = 'physical_data_link:bytes_sent' and timeseries_key in (16559390586733678333, 17708920380306668301) group by timeseries_key) select * from foo array join timestamp;

WITH foo AS
    (
        SELECT
            timeseries_key,
            arraySlice(arraySort(groupArray(timestamp)), -5) AS timestamp
        FROM measurements_cumulativeu64
        WHERE (timeseries_name = 'physical_data_link:bytes_sent') AND (timeseries_key IN (16559390586733678333, 17708920380306668301))
        GROUP BY timeseries_key
    )
SELECT *
FROM foo
ARRAY JOIN timestamp

Query id: e2e12f92-6dba-4ab9-8810-bcd2bcc861d1

┌───────timeseries_key─┬─────────────────────timestamp─┐
│ 16559390586733678333 │ 2024-02-23 21:15:24.904686484 │
│ 16559390586733678333 │ 2024-02-23 21:15:34.907132425 │
│ 16559390586733678333 │ 2024-02-23 21:15:44.909441456 │
│ 16559390586733678333 │ 2024-02-23 21:15:54.911694690 │
│ 16559390586733678333 │ 2024-02-23 21:16:04.913340258 │
│ 17708920380306668301 │ 2024-02-23 21:15:00.567296790 │
│ 17708920380306668301 │ 2024-02-23 21:15:10.571033980 │
│ 17708920380306668301 │ 2024-02-23 21:15:21.469836084 │
│ 17708920380306668301 │ 2024-02-23 21:15:31.473356779 │
│ 17708920380306668301 │ 2024-02-23 21:15:41.477481102 │
└──────────────────────┴───────────────────────────────┘

10 rows in set. Elapsed: 0.052 sec. Processed 475.44 thousand rows, 25.70 MB (9.19 million rows/s., 496.98 MB/s.)
Peak memory usage: 23.79 MiB.

```

**Comment by bnaecker** [comment]
Oh man ClickHouse is amazing. There's a [`LIMIT BY`](https://clickhouse.com/docs/en/sql-reference/statements/select/limit-by) clause, which takes the limit _within each group_. That's exactly what we want to do here.

**Comment by david-crespo** [comment]
Clickhouse wins

**Comment by david-crespo** [comment]
I know we talked about it in chat, but I could have been more specific about my use case in the issue description. What I really want is to be able, for a given timeseries, to select at most one point where `timestamp < @now - 1d` but _all_ the points where `timestamp >= @now - 1d`. So there are two different limits at work here (the latter implicitly not limited). Off the top of my head the only way I can think of to do that with `LIMIT BY` is something like this:

```sql
LIMIT 1 BY if(timestamp >= @now - 1d, timestamp, @now)
```

i.e., make sure all values before the cutoff have the same value, but all values after have unique values. The `@now` in the else could be any hard-coded timestamp.

**Comment by bnaecker** [comment]
That would be a really nice trick, but I think it unfortunately won't work. Here are the results running that against some historical data from dogfood:

```
shale :) select timeseries_key, start_time, timestamp, datum, t from measurements_cumulativeu64 where timeseries_name = 'physical_data_link:bytes_sent' and timeseries_key in (16559390586733678333) order by timeseries_key, start_time, timestamp desc limit 5 by if(timestamp >= toDateTime64('2024-02-23 21:15:14', 9), timestamp, toDateTime64('2024-02-23 21:15:14', 9)) as t;

SELECT
    timeseries_key,
    start_time,
    timestamp,
    datum,
    t
FROM measurements_cumulativeu64
WHERE (timeseries_name = 'physical_data_link:bytes_sent') AND (timeseries_key IN (16559390586733678333))
ORDER BY
    timeseries_key ASC,
    start_time ASC,
    timestamp DESC
LIMIT 5 BY if(timestamp >= toDateTime64('2024-02-23 21:15:14', 9), timestamp, toDateTime64('2024-02-23 21:15:14', 9)) AS t

Query id: 78deb64f-248b-4c76-961b-f326e12c4ba2

┌───────timeseries_key─┬────────────────────start_time─┬─────────────────────timestamp─┬──────datum─┬─────────────────────────────t─┐
│ 16559390586733678333 │ 1986-12-28 00:00:46.896537062 │ 2024-01-25 21:30:38.587647788 │ 1878381922 │ 2024-02-23 21:15:14.000000000 │
│ 16559390586733678333 │ 1986-12-28 00:00:46.896537062 │ 2024-01-25 21:30:28.586091033 │ 1878350551 │ 2024-02-23 21:15:14.000000000 │
│ 16559390586733678333 │ 1986-12-28 00:00:46.896537062 │ 2024-01-25 21:30:18.584888187 │ 1878318484 │ 2024-02-23 21:15:14.000000000 │
│ 16559390586733678333 │ 1986-12-28 00:00:46.896537062 │ 2024-01-25 21:30:08.582492734 │ 1878287390 │ 2024-02-23 21:15:14.000000000 │
│ 16559390586733678333 │ 1986-12-28 00:00:46.896537062 │ 2024-01-25 21:29:58.578260644 │ 1878255673 │ 2024-02-23 21:15:14.000000000 │
└──────────────────────┴───────────────────────────────┴───────────────────────────────┴────────────┴───────────────────────────────┘
┌───────timeseries_key─┬────────────────────start_time─┬─────────────────────timestamp─┬─────datum─┬─────────────────────────────t─┐
│ 16559390586733678333 │ 1986-12-28 00:01:31.534105368 │ 2024-02-23 21:16:04.913340258 │ 311337048 │ 2024-02-23 21:16:04.913340258 │
│ 16559390586733678333 │ 1986-12-28 00:01:31.534105368 │ 2024-02-23 21:15:54.911694690 │ 311301094 │ 2024-02-23 21:15:54.911694690 │
│ 16559390586733678333 │ 1986-12-28 00:01:31.534105368 │ 2024-02-23 21:15:44.909441456 │ 311264880 │ 2024-02-23 21:15:44.909441456 │
│ 16559390586733678333 │ 1986-12-28 00:01:31.534105368 │ 2024-02-23 21:15:34.907132425 │ 311202282 │ 2024-02-23 21:15:34.907132425 │
│ 16559390586733678333 │ 1986-12-28 00:01:31.534105368 │ 2024-02-23 21:15:24.904686484 │ 311166508 │ 2024-02-23 21:15:24.904686484 │
│ 16559390586733678333 │ 1986-12-28 00:01:31.534105368 │ 2024-02-23 21:15:14.902757391 │ 311131178 │ 2024-02-23 21:15:14.902757391 │
└──────────────────────┴───────────────────────────────┴───────────────────────────────┴───────────┴───────────────────────────────┘

11 rows in set. Elapsed: 0.031 sec. Processed 254.25 thousand rows, 17.15 MB (8.32 million rows/s., 560.91 MB/s.)
Peak memory usage: 12.47 MiB.

```

So the second block of results is what we really want. However, we also get the first block, which are much older than we'd like. Why? Although it's not totally clear, I think this is explained by the `LIMIT BY` documentation, which says:

> A query with the `LIMIT n BY expressions` clause selects the first n rows for each distinct value of `expressions`

There are two distinct values of `expressions` here,  which I've aliased to the `t` column. It picks `n` values for each of those, not the last value for the older group and `n` values for the later group. I.e., for each value of `t`, there are `n` results. Bummer.

So how can we do what you'd like? I think we could do it in SQL with some subqueries to select (1) the last result before the cutoff and (2) all the results after, and then (3) merge them with a `UNION`. But I think that's both pretty complicated and specialized to just this particular use case, where we have irregularly sampled data and don't know the time of the last sample before our time window (or even if it exists!).

It might be more expedient and simpler to support limiting table operations in OxQL, like `{first,last} k`. Then we can either write two OxQL queries to select the two time ranges (limiting the first), just as the console has been doing. Since OxQL supports subqueries, this need not be two API calls, as it was before.

But if two queries is still annoying, I think we have a few options. First, we could support a specific table operation like SQL's `UNION`, something to concatenate timeseries. Or, I think we can practically speaking do that with `group_by`. Since the data is non-overlapping, grouping by all the keys and taking the "sum" would work. Putting it all together:

```
{
    get collection_target:cpus_provisioned | filter timestamp < @now() - 1d | last 1;
    get collection_target:cpus_provisioned | filter timestamp >= @now() - 1d
} | group_by [id], sum
```

I kind of like the idea of a specific concatenating operation, since it doesn't require that we know the schema first, but that could be done later if we need it perhaps..

**Comment by bnaecker** [comment]
Hmm, actually your approach might work. The `start_time` ordering is confusing things, for reasons I don't yet understand. But if we remove that, and use a limit of 1 in each group, I think we get what you'd like:

```
shale :) select timeseries_key, start_time, timestamp, datum, t from measurements_cumulativeu64 where timeseries_name = 'physical_data_link:bytes_sent' and timeseries_key in (16559390586733678333) order by timeseries_key, timestamp desc limit 1 by if(timestamp >= toDateTime64('2024-02-23 21:15:14', 9), timestamp, toDateTime64('2024-02-23 21:15:14', 9)) as t;

SELECT
    timeseries_key,
    start_time,
    timestamp,
    datum,
    t
FROM measurements_cumulativeu64
WHERE (timeseries_name = 'physical_data_link:bytes_sent') AND (timeseries_key IN (16559390586733678333))
ORDER BY
    timeseries_key ASC,
    timestamp DESC
LIMIT 1 BY if(timestamp >= toDateTime64('2024-02-23 21:15:14', 9), timestamp, toDateTime64('2024-02-23 21:15:14', 9)) AS t

Query id: 60c4495d-0402-492b-8cc7-bcd4fe427b3d

┌───────timeseries_key─┬────────────────────start_time─┬─────────────────────timestamp─┬─────datum─┬─────────────────────────────t─┐
│ 16559390586733678333 │ 1986-12-28 00:01:31.534105368 │ 2024-02-23 21:16:04.913340258 │ 311337048 │ 2024-02-23 21:16:04.913340258 │
│ 16559390586733678333 │ 1986-12-28 00:01:31.534105368 │ 2024-02-23 21:15:54.911694690 │ 311301094 │ 2024-02-23 21:15:54.911694690 │
│ 16559390586733678333 │ 1986-12-28 00:01:31.534105368 │ 2024-02-23 21:15:44.909441456 │ 311264880 │ 2024-02-23 21:15:44.909441456 │
│ 16559390586733678333 │ 1986-12-28 00:01:31.534105368 │ 2024-02-23 21:15:34.907132425 │ 311202282 │ 2024-02-23 21:15:34.907132425 │
│ 16559390586733678333 │ 1986-12-28 00:01:31.534105368 │ 2024-02-23 21:15:24.904686484 │ 311166508 │ 2024-02-23 21:15:24.904686484 │
│ 16559390586733678333 │ 1986-12-28 00:01:31.534105368 │ 2024-02-23 21:15:14.902757391 │ 311131178 │ 2024-02-23 21:15:14.902757391 │
│ 16559390586733678333 │ 1986-12-28 00:01:31.534105368 │ 2024-02-23 21:15:04.900679588 │ 311066241 │ 2024-02-23 21:15:14.000000000 │
└──────────────────────┴───────────────────────────────┴───────────────────────────────┴───────────┴───────────────────────────────┘

7 rows in set. Elapsed: 0.038 sec. Processed 254.25 thousand rows, 17.15 MB (6.65 million rows/s., 448.49 MB/s.)
Peak memory usage: 25.13 MiB.
```

I do think this is now something different from the limiting table operations I thought we might want, like `first k` or `last k`. I'm not sure how to express it in OxQL nicely yet.

**Comment by bnaecker** [comment]
Ok, I've taken a stab at implementing this in #5478. It doesn't do _exactly_ what @david-crespo would like in a single query, selecting all the points in a time range and the latest point prior to that range. I think that's a pretty special case, and I'm not sure how to make that a first-class table operation in OxQL. Instead, that PR adds generic `first k` and `last k` operations. Combined with subqueries, that means we can fetch the desired results with something like:

```
{
    get collection_target:cpus_provisioned | filter timestamp < @now() - 1d | last 1;
    get collection_target:cpus_provisioned | filter timestamp >= @now() - 1d
} | group_by [id], sum
﻿
```

**Comment by david-crespo** [comment]
That sounds good to me. I don’t think a single query is necessary. It’s nice though that I can do multiple queries in a single API call.
