### ISSUE TITLE
what to do with zpool and physical_disk database tables after expungement

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/omicron#5558]
There is a comment in issue #4787 around what happens to database tables in
a sled that has been removed.  This section specifically:

```
## Database state
...

Besides those direct consumers, physical disks are referenced by the `zpool` 
table.  `zpool` is referenced by `dataset.pool_id` and some inventory tables.  
Again I think we can ignore inventory tables here.  `dataset` is referenced by 
`region.dataset_id` and `region_snapshot.dataset_id`.  I'm assuming that 
`physical_disk`, `zpool`, `dataset`, and `region` are well understood and covered 
by the open tickets around #4719 and Crucible region replacement.

```
_Originally posted by @davepacheco in https://github.com/oxidecomputer/omicron/issues/4787#issuecomment-2062209289_
     

The current plan for Crucible region replacement does not address what to do with
the `zpool` and `physical_disk` tables.

It may not be a problem to just leave them as they are, but I did want to call out that
at the moment, no special action is taken for these tables during the Crucible region
replacement work.

**Comment by davepacheco** [comment]
We discussed this briefly in today's update call and concluded that:

- eventually, we may want to clean up `zpool` and `physical_disk` records, as we want to clean up tons of other kinds of records (e.g., old blueprints, completed sagas, deleted silos/projects/instances/VPCs/etc.); and
- the presence of these records in the meantime is not a problem.  e.g., we won't accidentally provision to the zpool because we're already filtering for disks or sleds that are in-service.
