### ISSUE TITLE
Constrain source host allow-list checks to Nexus API only

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#5892]
Allow-list currently restricts the access to both the external DNS and API servers. A customer reported that the last-mile DNS addresses are often outside of their control and they can't configure the allow-list in a meaningful way to control the access to both types of endpoints. Their primary concern is API endpoints at this time so they would like the allow-list to be applied only to those endpoints.

**Comment by bnaecker** [comment]
One solution is to use the fact that Nexus is in its own VPC Subnet, [defined in `nexus_db_fixed_data::vpc_subnet`](https://github.com/oxidecomputer/omicron/blob/42f53321067077aa39976290c5c5365770667574/nexus/db-fixed-data/src/vpc_subnet.rs#L21). We could rewrite the logic for creating OPTE firewall rules implementing the allow list so that they only apply to this particular VPC Subnet. This loses one of the main benefits of this approach described in RFD 474: new services added later do not automatically pick up the allow-list. There may be other approaches too, but this one seems at least viable.

**Comment by bnaecker** [comment]
Here's another solution. The initial implementation created a new DB table for the allowlist itself, rather than storing it as VPC firewall rules directly, because it wasn't obvious how to correctly tag the rules as belonging to the allowlist as opposed to the builtin rules or others. That would make it difficult to update just the allowlist, since without tags, everything just appears to apply to the relevant VPC.

We could bite that bullet now, and store the rule implementing the allowlist directly in the VPC Firewall rule for the Nexus VPC Subnet. This isn't really any more brittle than the approach above, I don't think, and has the added benefit of removing a database table and corresponding lookup each time we need to forward firewall rules to the sled-agents.

**Comment by bnaecker** [comment]
Although this second option conflates the "allowlist" with the VPC firewall rules, I'm inclined to go that route. It removes a lot of code, since we completely get rid of the allowlist table and datastore methods. Instead, those delegate to existing VPC firewall rule methods. We also obviate one DB lookup when propagating these, although that's pretty minor.

At first glance, it seems to more tightly couple the firewall rules and the allowlist, but I'm not actually sure that's the case. We already rely on the rules for the Oxide VPC having no host filters as the indication that we can modify those rules to insert the allowlist. The reduction of several hundred lines of code seems like a reasonable cost to pay for noting that the allow list actually **is** the host filters in the firewall rule that applies to the Nexus VPC Subnet.

**Comment by bnaecker** [comment]
I talked offline with @jgallagher about the above approach. We both agree it seems reasonable, but I've encountered a bunch of technical administrivia which make this really difficult. As an example, we currently need to be able to set the allowlist from the big RSS transaction that implements rack initialization. That requires a static method on `DataStore`. However, all the code for interacting with VPC firewall rules requires instance methods on both `Nexus` and `DataStore` objects, most notably to retry the transaction in `vpc_update_firewall_rules()`.

I'd really rather not duplicate or reorganize any of that, since I think it's quite simple and nearly equivalent to only apply the allow list to Nexus's VPC Subnet firewall rule (there's exactly one today).
