### ISSUE TITLE
`/user/projects` endpoint

### ISSUE THREAD

**Issue by jessfraz** [oxidecomputer/omicron#593]
Just like with GitHub how you can be authorized to projects outside your org we describe similar in rfd 43 in that other orgs can still add users outside their org if they configure their setup to have cross org collaboration.

In the same vein, I think this calls for a `/user/projects` endpoint like github's https://docs.github.com/en/rest/reference/repos#list-repositories-for-the-authenticated-user

Otherwise, how can you list all your projects you have access to from the API?

**Comment by jessfraz** [comment]
im  curious how the console is doing this today @david-crespo jus wondering if you'd need this too?

**Comment by davepacheco** [comment]
Possibly related question: how do we know what Organization that an IdP User is part of the first time they log in?

**Comment by jessfraz** [comment]
happy to show you how i do this in google etc. its fairly standard

**Comment by jessfraz** [comment]
here is okta's mapping UI
<img width="1019" alt="Screen Shot 2022-01-13 at 9 07 35 AM" src="https://user-images.githubusercontent.com/1445228/149376199-a97719aa-0738-4e05-b08d-01ebfdb3057f.png">

**Comment by jessfraz** [comment]
it can map any strings to any strings on the other provider

**Comment by davepacheco** [comment]
That's helpful.  It seems like more specification is needed [in the RFD 115 section on how we configure the IdP](https://github.com/oxidecomputer/rfd/tree/0115/rfd/0115#our-products-saml-setup-flow) (or somewhere else).

**Comment by david-crespo** [comment]
In the console we just do it one org at a time, so users would have to go the project list for a particular org to find their project. This works in a basic sense even though it's mediocre, especially if users only have two or three orgs, which should be nearly everyone.

I've been trying to avoid putting much work into the multi-org use case because I don't have a good sense of how many users are going to be doing cross-org work and how often, so I'd rather make it really basic and then learn where to go next from real users.

Of course, from a console POV, if there _is_ a `/user/projects` endpoint, making a page for that is trivial so we can do it no problem. But I haven't pushed hard for it for the above reasons.

**Comment by jessfraz** [comment]
yeah i want the endpoint for the CLI so I'm saying we need it ;) so that you can easily list all your projects.

**Comment by jessfraz** [comment]
@davepacheco when we hook into okta we play around with the mappings

**Comment by jessfraz** [comment]
https://developer.okta.com/docs/guides/build-sso-integration/saml2/main/#prepare-your-integration

**Comment by davepacheco** [comment]
> when we hook into okta we play around with the mappings, but to be clear this is in the customers okta portal it is not in our UI, we don't need a screen for that in the console we will just setup the allowed mappings globally in our okta plugin goober thing

I don't understand how this can work.  How does Okta know anything about what Organizations have been configured in the Oxide system?

To be concrete, if an operator sets up the rack and creates organizations A and B (which do not exist in the IdP), then user Alice logs in, how do we know if Alice belongs in organization A or B?

**Comment by jessfraz** [comment]
When we code our integration we will tell them our mappings. Check out the link I linked

**Comment by jessfraz** [comment]
for example, today with okta + gsuite, I map the okta org I set for you all to automatically update the org you are in for gsuite, like that's how the flow needs to work or else this wont be helpful at all and just gets in the way. this is also the flow people expect since that's how like every thing works in okta / other providers (you'd want the things to be in sync) but its a one direction sync, from provider to oxide not oxide to provider

**Comment by davepacheco** [comment]
> Ideally they are using orgs that are already in the Idp that's the only way the mappings work, if they go rogue then we cant map..

I think this is the disconnect.  It sounds like you're assuming that Organizations come from the IdP.  Are you sure about that?  I ask because this is the first I'd heard of that, I don't see anything in RFD 44 about it, and I think there are several parts of RFD 44 that suggest this _isn't_ the case:

* there are APIs for creating and deleting Organizations in the rack.  (Maybe we have both local and IdP organizations?  Would local organizations ever have users?)
* RFD 44 says that users can be moved from one Organization to another by an admin with the appropriate permissions in the Oxide rack.  But if the Organization and User come from the IdP, how can the rack move the user between Orgs?
* RFD 44 says users and groups come from the IdP, but doesn't say that about Orgs.

Is there somewhere else this might be described in more detail?

----

Even if we decided that Organizations map to some entity in the IdP, I think that just pushes the question around: how do we know which entities in the IdP represent things that we should create Organizations for?

**Comment by jessfraz** [comment]
I think it could be either, ideally, I'd want to sync them from the Idp if possible but I know Okta has more params and can do more things like this whereas others might not be able to.

**Comment by jessfraz** [comment]
> RFD 44 says that users can be moved from one Organization to another by an admin with the appropriate permissions in the Oxide rack. But if the Organization and User come from the IdP, how can the rack move the user between Orgs?

To answer this, ideally when I update my Idp for a re-org, all the moving would automatically happen the next time the rack syncs with the idp and sees the changes.

> RFD 44 says users and groups come from the IdP, but doesn't say that about Orgs.

this is just an oversight apologies, user and groups are 100% not handled by oxide and no one wants us to, orgs is a nice to have if the idp supports it, otherwise they'd need to come from the rack, does that make sense?

**Comment by jessfraz** [comment]
we'd know because of the mappings, let me show you the okta UI sometime...
