### ISSUE TITLE
Early networking bails when mac addresses are not yet available

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/omicron#6064]
When mupdating rack 3, one of the switches failed to initialize. We found `switch1` with no configuration and `switch0` with what appeared to be a full configuration.

After digging through logs we found this error in the sled agent on the scrimlet attached to `switch1`

```
00:04:23.310Z ERRO SledAgent (HardwareMonitor): Failed to activate switch
    error = Early networking setup error: Error during request to Dendrite: unable to apply uplink port configuration: Error Response: status: 503 Service Unavailable; headers: {"content-type": "application/json", "x-request-id": "9ba0aa69-973f-4085-9f77-0112b585e69d", "content-length": "94", "date": "Sun, 28 Dec 1986 00:04:22 GMT"}; value: Error { error_code: None, message: "Service Unavailable", request_id: "9ba0aa69-973f-4085-9f77-0112b585e69d" }
```

which corresponds to this error in the dendrite logs

```
00:04:23.308Z INFO dpd: request completed
    error_message_external = Service Unavailable
    error_message_internal = No MAC addresses available
    latency_us = 265
    local_addr = [fd00:1122:3344:11f::2]:12224
    method = POST
    remote_addr = [fd00:1122:3344:11f::1]:61585
    req_id = 9ba0aa69-973f-4085-9f77-0112b585e69d
    response_code = 503
    server_id = 1
    unit = api-server
    uri = /port/qsfp0/settings?tag=omicron
```

so it seems that there is some sort of race condition between early networking and mac addresses being available from dendrite.

**Comment by rcgoodfellow** [comment]
Full dendrite log file is at

```
catacomb:/staff/rack3/BRM42220078/2024-07-12/oxide-dendrite_default.log.536112900
```

**Comment by augustuswm** [comment]
Links came up after restarting `sled-agent`

**Comment by bnaecker** [comment]
From a quick glance, it seems the early networking code calls this method:

https://github.com/oxidecomputer/omicron/blob/32f353d2104cc4c60943da1f527c0d2c01460011/sled-agent/src/bootstrap/early_networking.rs#L692

to determine if it can start making requests to Dendrite. That's not entirely accurate. The API server may be available, but without real MAC addresses from the Sidecar SP, it won't be able to create usable links. I recall discussion about this, that Dendrite should report when it's _really_ open for business, rather than just the API server being available. I can't find that now, but will keep looking.

In addition, the early-networking code should probably retry a 503, rather than wedging the whole sequence.

**Comment by askfongjojo** [comment]
The long-term fix is in https://github.com/oxidecomputer/dendrite/issues/1001. But we have a mitigation so this can be closed.

**Comment by bnaecker** [comment]
Just for clarity, I actually think the long-term fix is what's done in https://github.com/oxidecomputer/omicron/pull/6106, where the client retries operations that fail with a 503. The "ready for operation API" in https://github.com/oxidecomputer/dendrite/issues/1001 is a bit fraught IMO. A client could ask if Dendrite is ready, it says "Yes", and then promptly crashes and restarts. I think we have to generally just retry things until they work, otherwise we're open to TOCTOU bugs.
