### ISSUE TITLE
DNS servers should not respond to DNS requests until they know what to say

### ISSUE THREAD

**Issue by davepacheco** [oxidecomputer/omicron#6205]
(It's possible this is already the case.)

When we deploy new internal or external DNS servers, they may be immediately discovered by clients (both internal and external).  However, they won't come up with the correct contents of DNS.  They will probably respond to all queries with NXDOMAIN or by returning 0 records.  Both are probably wrong.  Instead, we should have these components not respond to DNS queries until they've received their initial DNS config from Nexus.

I'm hopeful this will be pretty easy because they only do DNS over UDP so they don't have to avoid starting the DNS server or anything.  They can hopefully just check some boolean (that gets updated when they get their first config from Nexus) and bail out of DNS request processing quickly.

**Comment by iximeow** [comment]
> (It's possible this is already the case.)

seems we already do better, in fact: in situations like this, the server will not believe itself authoritative for any zones, so all queries will get SERVFAIL.

i also checked that we'll behave similarly if the server is being provided a config that makes it authoritative over a new zone (e.g. either an initial config, or some new zone provided later): until a config update is committed, queries will be answered from the old generation, and all records are stored before a new config and new zones are commmitted. so both in case of an update adding or removing a zone, the answer will either be SERVFAIL if we're not authoritative, or correct w.r.t the records for the last update of that zone. we'll not return an NXDOMAIN or stale records.

as it turns out the easy case of "DNS server is on with no config" is tested by the [servfail test](https://github.com/oxidecomputer/omicron/blob/main/dns-server/tests/basic_test.rs#L293-L329), since that never advances the server from its initial blank slate configuration.

i'm less confident about testing the query-during-update-that-adds-or-removes-zone case. it's plausible enough to fuzz the server while adding and removing zones, testing that we never get an NXDOMAIN, but it feels like that's relatively little assurance we're actually testing the race? what do you think, would that be useful?

**Comment by davepacheco** [comment]
> seems we already do better, in fact: in situations like this, the server will not believe itself authoritative for any zones, so all queries will get SERVFAIL.

Ah, sorry for the red herring here, but thank you for verifying the behavior!

> i'm less confident about testing the query-during-update-that-adds-or-removes-zone case. it's plausible enough to fuzz the server while adding and removing zones, testing that we never get an NXDOMAIN, but it feels like that's relatively little assurance we're actually testing the race? what do you think, would that be useful?

I don't think so.  It's designed to be atomic (right?) and I'm not sure how you'd test what happens in the middle of it without introducing non-atomicity to it.

**Comment by iximeow** [comment]
> I'm not sure how you'd test what happens in the middle of it without introducing non-atomicity to it

i've found it very helpful to "testpoints" that are more or less a bag of shared AtomicBool to force specific orderings between async tasks and test otherwise-narrow races, so the server would still behave atomically but the test would be something like:
* start an update
* pause the update task just before committing a new `CurrentConfig` and its generation
* [elsewhere] issue a query, expect SERVFAIL
* resume the update task
* issue the query again, expect an AAAA record

(though now that i've said it, i suppose here there's are much better things to spend time on at the moment)

so instead, onward!
