### ISSUE TITLE
Metrics: Queries of sometimes return fewer data points

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#6744]
OxQL queries sometimes return no or a lot less data points when many concurrent OxQL queries are in progress. It is likely a situation of system under heavy load. I've attached the logs for two almost identical queries (one using the `@now - 15s` criteria whereas the other one I retried with the exact start/end timestamps for comparison.

[fan_speed-clickhouse-succeed.log](https://github.com/user-attachments/files/17217227/fan_speed-clickhouse-succeed.log)
[fan_speed-nexus-succeed.log](https://github.com/user-attachments/files/17217229/fan_speed-nexus-succeed.log)
[fan_speed-nexus-failed.log](https://github.com/user-attachments/files/17217230/fan_speed-nexus-failed.log)
[fan_speed-clickhouse-failed.log](https://github.com/user-attachments/files/17217231/fan_speed-clickhouse-failed.log)

The "failed" ones are from the `@now - 15s` timestamp filter which returned much fewer points than the "succeed" ones.

If query service degrades due to load, it'll be better to return a 503 error than to succeed without the right responses.

**Comment by askfongjojo** [comment]
More context: The issue didn't happen when I had prometheus scrape a handful of timeseries (via a tool named json_exporter that converts json output to a format suitable for prometheus ingestion). The problem began to show up consistently when I added more scraping jobs. The current OxQL invocation setup can be found [here](https://github.com/oxidecomputer/product-assurance/blob/main/metrics/monitoring/json_exporter/config.yml).

**Comment by bnaecker** [comment]
Using `@now() - 15s` and two explicit timestamp bounds aren't quite the same query, even if you take the exact timestamps from the first query and plug them in the second. The key is that data is always being added into the database, on an interval that the producer controls. When you do `@now() - 15s`, you might have hit the database right _before_ a batch of data was inserted. If you run the query a second time, using the timestamps from the first query, then the data might now have been inserted and processed, so the query returns more data despite using exactly the same time bounds.


I'm not positive, but this might be more obvious under heavy load. Suppose that ClickHouse takes longer to process a given batch of data that `oximeter` inserts from the producer. Then the time window over which the query would return less data than you expect is widened. In fact, the number of samples you expect to see in any query with a timestamp filter like `timestamp > @now() - T` looks like a sawtooth. Right when the data is inserted, all of those samples are available. Imagine running the query very quickly over time -- as it progresses, you'd get less and less data each time, because the time window defined by `@now() - T` is sliding forward, while the data in the database is still static during this interval. It "jumps up" again when the next batch is inserted.

I hope that makes sense. I'd love to see what happens if we run the _same_ query, with explicit timestamps, both in light- and heavy-load scenarios. From your initial testing and some by @bcantrill, it seems like there's substantial variability in the query latency, which I'm working to diagnose. But more examples of that are always helpful!

**Comment by askfongjojo** [comment]
@bnaecker: Thanks for looking into this issue / user error! Yes, it makes total sense.

As the data points have timestamps that are about 1 second apart, I didn't consider the fact that the collector invocations may be not as periodic. Here is a snippet of the oximeter log on rack2 which confirms that the `management-gateway` producer data collection intervals (with the 2 MG instances combined) can be anywhere from 1 to 30s:
```
03:15:05.470Z DEBG oximeter (oximeter-agent): collecting from producer
03:15:06.165Z DEBG oximeter (oximeter-agent): collecting from producer
03:15:36.081Z DEBG oximeter (oximeter-agent): collecting from producer
03:15:45.676Z DEBG oximeter (oximeter-agent): collecting from producer
03:15:54.763Z DEBG oximeter (oximeter-agent): collecting from producer
03:15:55.676Z DEBG oximeter (oximeter-agent): collecting from producer
03:16:06.743Z DEBG oximeter (oximeter-agent): collecting from producer
03:16:06.743Z DEBG oximeter (oximeter-agent): collecting from producer
03:16:31.557Z DEBG oximeter (oximeter-agent): collecting from producer
03:16:31.715Z DEBG oximeter (oximeter-agent): collecting from producer
03:16:38.159Z DEBG oximeter (oximeter-agent): collecting from producer
03:16:42.130Z DEBG oximeter (oximeter-agent): collecting from producer
03:16:46.969Z DEBG oximeter (oximeter-agent): collecting from producer
03:16:49.487Z DEBG oximeter (oximeter-agent): collecting from producer
03:16:52.096Z DEBG oximeter (oximeter-agent): collecting from producer
03:16:56.883Z DEBG oximeter (oximeter-agent): collecting from producer
03:17:03.505Z DEBG oximeter (oximeter-agent): collecting from producer
03:17:24.922Z DEBG oximeter (oximeter-agent): collecting from producer
03:17:32.808Z DEBG oximeter (oximeter-agent): collecting from producer
03:17:41.369Z DEBG oximeter (oximeter-agent): collecting from producer
03:17:42.368Z DEBG oximeter (oximeter-agent): collecting from producer
03:17:49.851Z DEBG oximeter (oximeter-agent): collecting from producer
03:17:49.851Z DEBG oximeter (oximeter-agent): collecting from producer
03:18:03.624Z DEBG oximeter (oximeter-agent): collecting from producer
03:18:03.630Z DEBG oximeter (oximeter-agent): collecting from producer
03:18:27.046Z DEBG oximeter (oximeter-agent): collecting from producer
03:18:37.047Z DEBG oximeter (oximeter-agent): collecting from producer
03:18:43.555Z DEBG oximeter (oximeter-agent): collecting from producer
03:18:47.048Z DEBG oximeter (oximeter-agent): collecting from producer
03:18:51.598Z DEBG oximeter (oximeter-agent): collecting from producer
03:18:57.049Z DEBG oximeter (oximeter-agent): collecting from producer
03:19:04.403Z DEBG oximeter (oximeter-agent): collecting from producer
03:19:12.755Z DEBG oximeter (oximeter-agent): collecting from producer
03:19:25.012Z DEBG oximeter (oximeter-agent): collecting from producer
03:19:37.571Z DEBG oximeter (oximeter-agent): collecting from producer
03:19:39.676Z DEBG oximeter (oximeter-agent): collecting from producer
03:19:44.615Z DEBG oximeter (oximeter-agent): collecting from producer
03:19:48.403Z DEBG oximeter (oximeter-agent): collecting from producer
03:19:52.035Z DEBG oximeter (oximeter-agent): collecting from producer
03:19:53.654Z DEBG oximeter (oximeter-agent): collecting from producer
03:20:05.700Z DEBG oximeter (oximeter-agent): collecting from producer
03:20:09.457Z DEBG oximeter (oximeter-agent): collecting from producer
03:20:26.395Z DEBG oximeter (oximeter-agent): collecting from producer
03:20:31.339Z DEBG oximeter (oximeter-agent): collecting from producer
03:20:38.573Z DEBG oximeter (oximeter-agent): collecting from producer
03:20:44.714Z DEBG oximeter (oximeter-agent): collecting from producer
```
It'd appear the longest duration in which there is at least 1 data point may not be guaranteed.  I chose the last 15-second filter to avoid reading a lot of data unnecessarily. Now that it's clear there may be longer time gaps, I'll experiment with scraping using a longer span of time to avoid hitting those gaps in data points.
