### ISSUE TITLE
Non-fleet admin user hit 404 error when attaching IP pool to internet gateway

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/omicron#6813]
This may be a similar issue to #5883 and #5508 as IP pools are system-owned objects that are partially accessible by end-users based on silo associations.

```
$ oxide internet-gateway create \
    --project 'test' \
    --description 'dc2 gateway' \
    --vpc default \
    --name dc2
{
  "description": "dc2 gateway",
  "id": "3ac306ab-d551-40f4-92e2-3250b2081eac",
  "name": "dc2",
  "time_created": "2024-10-10T01:07:28.651062Z",
  "time_modified": "2024-10-10T01:07:28.651062Z",
  "vpc_id": "6c715b4a-308e-4b4e-9388-2485964f72e4"
}

$ oxide internet-gateway ip-pool attach \
    --project 'test' \
    --vpc default \
    --gateway dc2 \
    --ip-pool dc2 \
    --name dc2-ig \
    --description 'test vpc dc2 gateway attachment'
error
Error Response: status: 404 Not Found; headers: {"content-type": "application/json", "x-request-id": "fcb203f1-63f4-4cbd-b4e0-0311a7223a58", "content-length": "145", "date": "Thu, 10 Oct 2024 01:07:33 GMT"}; value: Error { error_code: Some("ObjectNotFound"), message: "not found: ip-pool with name \"dc2\"", request_id: "fcb203f1-63f4-4cbd-b4e0-0311a7223a58" }
```
The same user is able to create a floating IP address from the IP pool in question:
```
$ oxide floating-ip create \
    --project test \
    --name dc2-igw \
    --description 'floating ip for dc2 gateway' \
    --pool dc2
{
  "description": "floating ip for dc2 gateway",
  "id": "5b5e8205-0bcf-45cc-ba2b-68b009ebcafe",
  "ip": "172.20.27.152",
  "ip_pool_id": "390523f5-ab8d-4dd6-b60f-2fcfb4df1c5c",
  "name": "dc2-igw",
  "project_id": "b7f06e48-93a9-43a1-abcd-c3601b4bc8dc",
  "time_created": "2024-10-10T01:16:16.189569Z",
  "time_modified": "2024-10-10T01:16:16.189569Z"
}
```

**Comment by david-crespo** [comment]
Probably this

https://github.com/oxidecomputer/omicron/blob/0640bb277df110f3e740464bf4bacdf2bd24c897/nexus/src/app/internet_gateway.rs#L206

**Comment by david-crespo** [comment]
We have to hack around this authz issue for the existing silo-scoped IP pool list and fetch operations. For list, we manually check that the user can list children of the silo, implicitly treating these as children of the silo. For fetching an individual pool, it's a worse hack because it's a two parter: on the pool lookup we check that the user has `CreateChild`, which means they can allocate IPs. Then we manually check that the pool is linked to the silo. That is probably what we need to do here, at least as a short term fix.

https://github.com/oxidecomputer/omicron/blob/9a5441f4ee59708fa2597beaf39cee3cfb36707e/nexus/src/app/ip_pool.rs#L78-L123
