### ISSUE TITLE
`omicron-ls-apis::test_dependencies` requires GitHub credentials or git rewrite rules

### ISSUE THREAD

**Issue by iliana** [oxidecomputer/omicron#6839]
@andrewjstone reported the following issue with the new test added in #6831 which I can trivially reproduce:

```
$ cargo nextest run -p omicron-ls-apis
info: experimental features enabled: setup-scripts
    Finished `test` profile [unoptimized + debuginfo] target(s) in 1.03s
------------
 Nextest run ID 4e62629e-50cf-41fd-98eb-f159421dac1b with nextest profile: default
    Starting 1 test across 3 binaries
     Running [ 00:00:03] [                                                                                            ] 0/1: 1 running, 0 passed, 0 skipped
        FAIL [   4.367s] omicron-ls-apis::test_dependencies test_api_dependencies

--- STDOUT:              omicron-ls-apis::test_dependencies test_api_dependencies ---

running 1 test
test test_api_dependencies ... FAILED

failures:

failures:
    test_api_dependencies

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 4.34s


--- STDERR:              omicron-ls-apis::test_dependencies test_api_dependencies ---
thread 'test_api_dependencies' panicked at dev-tools/ls-apis/tests/test_dependencies.rs:25:5:
assertion `left == right` failed: stderr:
loading metadata for workspace omicron from current workspace
loading metadata for workspace crucible from /home/iliana/.cargo/git/checkouts/crucible-f3b5bdecdc6486d6/2b88ab8/Cargo.toml
loading metadata for workspace maghemite from /home/iliana/.cargo/git/checkouts/maghemite-de41bdd6c14939ab/056283e/Cargo.toml
loading metadata for workspace propolis from /home/iliana/.cargo/git/checkouts/propolis-12517f89d3d9f483/11371b0/Cargo.toml
Error: loading metadata

Caused by:
    `cargo metadata` exited with an error:     Blocking waiting for file lock on package cache
        Updating git repository `https://github.com/oxidecomputer/dendrite`
    error: failed to get `common` as a dependency of package `ddm v0.1.0 (/home/iliana/.cargo/git/checkouts/maghemite-de41bdd6c14939ab/056283e/ddm)`

    Caused by:
      failed to load source for dependency `common`

    Caused by:
      Unable to update https://github.com/oxidecomputer/dendrite?branch=main#4cdc7d7e

    Caused by:
      failed to fetch into: /home/iliana/.cargo/git/db/dendrite-627b239a911c6241

    Caused by:
      failed to authenticate when downloading repository

      * attempted to find username/password via git's `credential.helper` support, but failed

      if the git CLI succeeds then `net.git-fetch-with-cli` may help here
      https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

    Caused by:
      failed to acquire username/password from local configuration


  left: 1
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   Canceling due to test failure
------------
     Summary [   4.369s] 1 test run: 0 passed, 1 failed, 0 skipped
        FAIL [   4.367s] omicron-ls-apis::test_dependencies test_api_dependencies
error: test run failed
```

This test works okay if you have your system configured in a particular way (either a GitHub token configured or a way to rewrite the HTTPS URL to an SSH one). This is a new requirement to run tests locally that I'd like to avoid having.

**Comment by iliana** [comment]
Additionally there's a test flake if the Omicron tests take more than an hour to get to `cargo xtask ls-apis apis`:

https://github.com/oxidecomputer/omicron/runs/31428158524
https://buildomat.eng.oxide.computer/wg/0/details/01J9YK8K5ASNHCKRDKBKD97KFT/DbLBuHhEEklJzGRMi7NxyxdZmoqz8wsZNyoMVGTIZVnvCvch/01J9YK99F56A9R34C76TTFCE0Y#S4415

Same root cause.

**Comment by iliana** [comment]
I think I have a decent workaorund for the outside-of-CI issue that I'll get a PR up for soon. The workaround I have planned for the other issue is to move the separate `cargo xtask ls-apis` calls to a different Buildomat job>

**Comment by davepacheco** [comment]
Sorry for the trouble here.

For the CI issue, I had worked around this previously by explicitly running these tests first.  I'll take a look at your other PR and also whether that approach might work here.

As for the local issue: I'm not sure how to avoid this.  Here's what I think is true (though I'm sure some of this isn't quite right):

- Dendrite is private and so requires cloning it over `ssh` or `https`.
- Cloning over `https` requires specifying the username and using a GitHub access token associated with that GitHub account.
- Cloning over `ssh` requires specifying the username and using an ssh key associated with that GitHub account.
- Our [use of Dendrite in Maghemite](https://github.com/oxidecomputer/maghemite/blob/056283eb02b6887fbf27f66a215662520f7c159c/Cargo.toml#L104-L112) (and I think other repos but I'm not sure) refers to it by `https`.
- In general, our approach with using private repos in CI has been to (1) [use Git rewrite rules to change any ssh URLs to https ones](https://github.com/oxidecomputer/omicron/blob/main/tools/include/force-git-over-https.sh), and (2) [have buildomat create an access token for the job (which expires after one hour)](https://github.com/oxidecomputer/buildomat/?tab=readme-ov-file#configuration).  This also requires telling Cargo to clone with the git CLI ([what that error message refers to](https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli)).
- I gather from discussion in oxide-q&a (2024-08-30) that it is common practice for people to have their own local rewrite rules that rewrite https URLs to ssh ones.  This solves the local problem, but is another one-time step people have to know about.  At the very least, we should document it.

@rcgoodfellow mentioned in that chat that we could use ssh URLs here and rely on rewrite rules in CI.  @sunshowers mentioned this would be a big cross-repo flag day (I didn't quite follow this).

**Comment by iliana** [comment]
#6840 is a hack (albeit not one that works in CI yet) to modify the environment of the `cargo metadata` command to try to fetch the repo over SSH if HTTPS fails. This is essentially the git rewrite rules option but invisible to the end user.

> Cloning over ssh requires specifying the username and using an ssh key associated with that GitHub account.

(Not the username part -- the username is always `git` in a GitHub SSH URL.)

**Comment by sunshowers** [comment]
> @rcgoodfellow mentioned in that chat that we could use ssh URLs here and rely on rewrite rules in CI. @sunshowers mentioned this would be a big cross-repo flag day (I didn't quite follow this).

The issue here is that we have a bunch of HTTPS git dependencies, and if we want those dependencies' types to be unified, we'd have to go around changing all of them to SSH roughly simultaneously. That seems to be a lot more work than using rewrite rules locally.

Agreed that we should document this better.

> Our use of Dendrite in Maghemite (and I think other repos but I'm not sure) refers to it by https.

Is pulling Dendrite down an important part of what ls-apis does?

**Comment by davepacheco** [comment]
@sunshowers @iliana and I just discussed at some length.  It's recorded in the weekly update huddle.  Conclusions:

- Dendrite is more the exception than the rule.  As a policy, we open-source everything we can, and Dendrite is currently the only thing `ls-apis` looks at that's not public.
- At the very least, we want to move the `cargo xtask ls-apis` to earlier in the build-and-test script so that it happens even before the main build.  This should cause Cargo to fetch everything it needs even earlier, hopefully eliminating the CI flakes.
- For now, we'll polish up #6840 such that it reports clearly what it tried and what it found so that if the fallback behavior goes badly, the user can know why.

The net result of this should be:

- CI should work reliably (*: given the 60-minute token limit with no refresh, there's no way to really guarantee this -- about _anything_ that uses private repos, but we can make it arbitrarily unlikely)
- Things should already be working for anybody who is using GitHub access tokens to clone Omicron and its dependencies.
- Things should already be working for anybody who has ssh rewrite rules in place to clone Omicron and its dependencies (which use https URLs) using ssh.
- The fallback introduced in #6840 should fix things for anybody who normally uses ssh but doesn't already have the rewrite rules (at least me and @andrewjstone -- unclear who else is in this bucket).

One downside is that the crate-timings will become less useful while this remains in place.

We considered a few alternatives to #6840:

- Document (blast to all@ + update README and the build-and-test docs (both simulated and non-simulated)) that if you're using ssh to clone things, you need to set up the Git rewrite rules.  A big downside here is that it makes other people on the team do work to deal with this problem, it's easy to forget to do, and it doesn't fail all that gracefully if you forget.
- Have a tool (either an `ls-apis` subcommand or -- if the Rust build itself is taking that long --) that _just_ causes Cargo to fetch Dendrite into its cache.  Document (in the same ways as above) that people have to run that after an initial clone and any time the Maghemite dependency changes.  This has the same downsides as above.
- Make the test only run in CI.  This doesn't help that much because you still run into all these problems if you do need to run this test locally (because you broke the thing it's checking).
- Switching Maghemite to use a git dependency to access Dendrite.  This would make it different from all of our public deps, and pushes the problem to the people already using access tokens to build Omicron and its dependencies.

**Comment by davepacheco** [comment]
> > Our use of Dendrite in Maghemite (and I think other repos but I'm not sure) refers to it by https.
> 
> Is pulling Dendrite down an important part of what ls-apis does?

Answered offline, but for the record: yes.  Part of what it does is look at the components we ship out of these other repositories and see what APIs they depend on.  Those aren't visible from Omicron's metadata.
