### ISSUE TITLE
[api] Document that null `auto_restart_policy` means best effort

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/omicron#6957]
This is the logic:

https://github.com/oxidecomputer/omicron/blob/d4263cb47512582f245b95e6dd046e84416baf2d/nexus/db-model/src/instance.rs#L422-L424

But it's not reflected in the doc comments on the instance create and update request bodies:

https://github.com/oxidecomputer/omicron/blob/d4263cb47512582f245b95e6dd046e84416baf2d/nexus/types/src/external_api/params.rs#L1138-L1159

**Comment by hawkw** [comment]
Ah, I see what happened: I remembered writing a comment that actually explained this on one of the API types...but, it turns out it was the `InstanceAutoRestartStatus` type that's part of the instance views _returned_ by the API, not on the params type:

https://github.com/oxidecomputer/omicron/blob/c274c16687af235efaf3ce0e8063ae100ba7434b/common/src/api/external/mod.rs#L1228-L1240

I'll update the params type to have a better doc comment.
