### ISSUE TITLE
Instance Creation should not *start* instance, just create it

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/omicron#720]
Currently, the act of merely "creating" and instance triggers it to begin running as well. In a fully device-less world, this has functioned as a convenience, but within the context of attaching disks and network interfaces, this becomes more of a pain.

In a world without hot-plug, consider the following:
- You want to create an instance
- You want to attach a disk to it

If you call "project_create_instance", the instance is created, immediately transitions to running, and must be stopped before a disk can be attached.

Instead, I propose that instances are initialized with the "Stopped" state, and only become allocated to a particular sled once explicitly started via `instance_start`. This will provide a created-but-not-started window in which devices may be attached.

**Comment by leftwo** [comment]
As an option could you choose (via. some mechanism, click-box, option..) that you want to both create and start an instance all at the same time?  I know there can be times when I want to create an instance without starting it, but I also sometimes want to create and start, and I don't want to have that "create and start" be two trips through some UI or a second command to send after the first finishes.

**Comment by david-crespo** [comment]
Cloud providers are not super clear on this in their docs, but I think that rather than creating instances in a stopped state, they solve this problem by letting you pass more elaborate configuration at create time. The end result is the same — you end up with a running instance configured the way you want, but the default behavior for a created instance is to start it (I think).

https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert#examples
https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/create-or-update
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html
https://docs.digitalocean.com/reference/api/api-reference/#operation/create_droplet

**Comment by smklein** [comment]
So it seems like we have (at least?) two reasonable choices here:

1. Instances are created as "stopped", and must be explicitly "started". From the console, we could execute "instance create", "attach devices" and "instance boot" one after another when a user fills out the instance creation form. I dunno if this conflicts with design principles of the console, however, as this would mean a single "web console" action corresponds with multiple "CLI" actions. IMO this option would keep our CLI "simpler", at the cost of occasionally needing to make multiple calls.

2. The `InstanceCreate` structure passed as a part of [`project_instances_post`](https://github.com/oxidecomputer/omicron/blob/0ca3b472c9453a2248016858ab9015e8298100d5/nexus/src/external_api/http_entrypoints.rs#L766-L770) could grow a fair bit, encapsulating the parameters which would also be passed to the "attach_{disk,nic}" calls. This seems aligned with other cloud providers, but slightly more complex.

When I wrote this issue, I think I had been leaning towards (1), but based on this feedback, option (2) may be more intuitive. Thoughts?

**Comment by davepacheco** [comment]
Along the lines of what @david-crespo suggested, I've been assuming that `params::InstanceCreate` would grow more configuration around NICs and disks for this reason.  It could also include an optional desired state ("stopped" or "running") to give people this choice.  My expectation from using other systems is that Instances would start "running" by default.

Separately, I think you're right @smklein that Instances should only be allocated to a particular Sled when they're started.  I think we're going to want to split the current "instance-provision" saga into at least two: once that creates an Instance and any related resources (e.g., Disks and NICs provided with the initial create request) for the very first time, and one that "starts" it, which would involve allocating runtime resources (like a Sled) and starting it running.

**Comment by rzezeski** [comment]
Ugh, lol, sorry. I was writing a comment, realized my comment was unnecessary, went to cancel it but accidentally hit close issue. Sigh, between dropping a bag of sharkfins and closing an issue I'm not remotely responsible for; I'm not sure what's worse.

**Comment by rmustacc** [comment]
> Along the lines of what @david-crespo suggested, I've been assuming that `params::InstanceCreate` would grow more configuration around NICs and disks for this reason. It could also include an optional desired state ("stopped" or "running") to give people this choice. My expectation from using other systems is that Instances would start "running" by default.

I do believe this is the common expectation of most users and probably most creation is create/start being the default. Overriding via additional params probably makes sense especially as we get to things like how can I make sure I'm attached to vnc/serial before things start.



> Separately, I think you're right @smklein that Instances should only be allocated to a particular Sled when they're started. I think we're going to want to split the current "instance-provision" saga into at least two: once that creates an Instance and any related resources (e.g., Disks and NICs provided with the initial create request) for the very first time, and one that "starts" it, which would involve allocating runtime resources (like a Sled) and starting it running.

One word of caution with this approach is that it does mean we can end up being unable to start instances later in time or restart them if we're not careful. I don't think we want resource reservations for CPU/memory while instances are stopped, but it does mean we need to make sure we have good messaging and testing around the can't schedule this VM again because I'm out of resources.
